### ISSUE TITLE
xsession errors

### ISSUE THREAD

**Issue by freefreeno** [bikass/korla#11]
(xfce4-session:21811): xfce4-session-WARNING **: 13:32:28.104: gpg-agent returned no PID in the variables
(xfdesktop:21827): Gtk-WARNING **: 13:32:28.438: Theme directory categories/scalable of theme korla has no size field
(xfdesktop:21827): Gtk-WARNING **: 13:32:28.438: Theme directory categories/symbolic of theme korla has no size field
(xfdesktop:21827): Gtk-WARNING **: 13:32:28.438: Theme directory emblems/symbolic of theme korla has no size field
(xfdesktop:21827): Gtk-WARNING **: 13:32:28.439: Theme directory notifications/scalable of theme korla has no size field
(pamac-tray:21828): Gtk-WARNING **: 13:32:28.445: Theme directory categories/scalable of theme korla has no size field
(pamac-tray:21828): Gtk-WARNING **: 13:32:28.445: Theme directory categories/symbolic of theme korla has no size field
(pamac-tray:21828): Gtk-WARNING **: 13:32:28.445: Theme directory emblems/symbolic of theme korla has no size field
(pamac-tray:21828): Gtk-WARNING **: 13:32:28.445: Theme directory notifications/scalable of theme korla has no size field
(xfce4-panel:21822): Gtk-WARNING **: 13:32:28.458: Theme directory categories/scalable of theme korla has no size field
(xfce4-panel:21822): Gtk-WARNING **: 13:32:28.458: Theme directory categories/symbolic of theme korla has no size field
(xfce4-panel:21822): Gtk-WARNING **: 13:32:28.458: Theme directory emblems/symbolic of theme korla has no size field
(xfce4-panel:21822): Gtk-WARNING **: 13:32:28.458: Theme directory notifications/scalable of theme korla has no size field
(nm-applet:21833): Gtk-WARNING **: 13:32:28.528: Theme directory categories/scalable of theme korla has no size field
(nm-applet:21833): Gtk-WARNING **: 13:32:28.528: Theme directory categories/symbolic of theme korla has no size field
(nm-applet:21833): Gtk-WARNING **: 13:32:28.528: Theme directory emblems/symbolic of theme korla has no size field
(nm-applet:21833): Gtk-WARNING **: 13:32:28.528: Theme directory notifications/scalable of theme korla has no size field
(wrapper-2.0:21864): Gtk-WARNING **: 13:32:28.613: Negative content width -1 (allocation 1, extents 1x1) while allocating gadget (node button, owner PulseaudioButton)
(wrapper-2.0:21864): Gtk-WARNING **: 13:32:28.615: Theme directory categories/scalable of theme korla has no size field
(wrapper-2.0:21864): Gtk-WARNING **: 13:32:28.615: Theme directory categories/symbolic of theme korla has no size field
(wrapper-2.0:21864): Gtk-WARNING **: 13:32:28.615: Theme directory emblems/symbolic of theme korla has no size field
(wrapper-2.0:21864): Gtk-WARNING **: 13:32:28.615: Theme directory notifications/scalable of theme korla has no size field
(Thunar:21824): Gtk-WARNING **: 13:32:33.298: Theme directory categories/scalable of theme korla has no size field
(Thunar:21824): Gtk-WARNING **: 13:32:33.298: Theme directory categories/symbolic of theme korla has no size field
(Thunar:21824): Gtk-WARNING **: 13:32:33.298: Theme directory emblems/symbolic of theme korla has no size field
(Thunar:21824): Gtk-WARNING **: 13:32:33.298: Theme directory notifications/scalable of theme korla has no size field
(mousepad:21898): Gtk-WARNING **: 13:32:38.009: Theme directory categories/scalable of theme korla has no size field
(mousepad:21898): Gtk-WARNING **: 13:32:38.009: Theme directory categories/symbolic of theme korla has no size field
(mousepad:21898): Gtk-WARNING **: 13:32:38.009: Theme directory emblems/symbolic of theme korla has no size field
(mousepad:21898): Gtk-WARNING **: 13:32:38.009: Theme directory notifications/scalable of theme korla has no size field

And they keep going. I removed the light version and also reinstalled the icons but the same errors occur.

**Comment by bikass** [comment]
I think I fixed those. Check if everything is fine.
