### ISSUE TITLE
Logout,suspend,shutdown,restart and hibernate icons.

### ISSUE THREAD

**Issue by freefreeno** [bikass/korla#12]
The logout and lock screen buttons need to be just a little darker because if you have say a grey and black Mac theme then the grey on these buttons will blend in with the grey on the theme. I am on xfce and when you click the logout icon on the whisker menu it will bring up a small box with logout,restart,shutdown,suspend sleep and hibernate and you choose the one you want. Since I use a MAC theme those icons blend in with the grey buttons on my theme.

**Comment by bikass** [comment]
Could you show screenshot how it looks. And maybe name of theme you using.
