### ISSUE TITLE
Latte Dock and KTorrent

### ISSUE THREAD

**Issue by Digitalone1** [bikass/korla#13]
Can you please change latte-dock icon? 

Original one has L inside:
![screenshot_20190224_124133](https://user-images.githubusercontent.com/25790525/53298707-02eb3500-3832-11e9-8f53-15f370161fb9.png)
Actual korla one is not good integrated:
![screenshot_20190224_124406](https://user-images.githubusercontent.com/25790525/53298711-05e62580-3832-11e9-80e3-f7033c4deb82.png)

You can also remove symlink from /apps/scalable and original one is replaced if you don't want to draw it.

And if you do KTorrent icon similar to original one with the arrow down would be appreciated:
![ktorrent](https://user-images.githubusercontent.com/25790525/53298751-7f7e1380-3832-11e9-8688-0a836ea9ba2a.png)

Thanks.

**Comment by bikass** [comment]
Changed those two icons. Check if they are ok for you.

**Comment by Digitalone1** [comment]
Great. Thanks.
