### ISSUE TITLE
Index.theme structure and panel icons not scalable

### ISSUE THREAD

**Issue by Digitalone1** [bikass/korla#15]
Hello, I made a cleanup in index.theme files. All categories now have only 1 scalable and 1 symbolic entry (except for panel icons, I didn't change them). It works to me, let me know if you find some issues.

I discovered something that may fix panel icons issue (but I can't test it on my system, Plasma themes do not allow to change panel icons). It seems that panel icons SHOULD BE "fixed" type, not "scalable". Looking into other themes index.theme files, there are no scalable entries for panel icons. They are ONLY fixed.

An example from Papirus:
```
[16x16/panel]
Context=Status
Size=16
Type=Fixed

[16x16@2x/panel]
Context=Status
Size=16
Scale=2
Type=Fixed

[22x22/panel]
Context=Status
Size=22
Type=Fixed

[22x22@2x/panel]
Context=Status
Size=22
Scale=2
Type=Fixed

[24x24/panel]
Context=Status
Size=24
Type=Fixed

[24x24@2x/panel]
Context=Status
Size=24
Scale=2
Type=Fixed
```

Same is for Numix theme. Breeze theme has no entries for panel icons inside index.theme.

You can try to change entries for panel icons in korla index.theme:
```
[panel/scalable]
Context=Status
Size=16
Type=Fixed

[panel/scalable]
Context=Status
Size=22
Type=Fixes

[panel/scalable]
Context=Status
Size=24
Type=Fixes
```

If this won't fix, I think the only way is to make png fixed icons for 16px, 22px and 24px sizes.

**Comment by bikass** [comment]
Hi, panel icons are from Papirus. In papirus everything is fine with scaling. In our theme I need to use 22x22 icons because 16x16 shows up bigger. If I change index with "fixed" I'm getting bigger icons even with 22x22. 
Just tried to create two folders 16x16 and 22x22, still some icons are bigger.
So, no progress here :) no changes. Works for time being. 
Would it be possible for you to instal VM of some distro (Ubuntu budgie), and mabye to look at this issue?

**Comment by Digitalone1** [comment]
No, bikass, I read papirus [index.theme](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/blob/master/Papirus/index.theme) and panel entries are all `Type=Fixed`.

Can you link me where you saw an index file with panel icons of scalable types?

I'm afraid you have to do something like this:
- delete panel/scalable directory
- create panel/16, panel/22 and panel/24 directories
- files in 16 should have `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" version="1.1">`, 22 should have `<svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" version="1.1">` and 24 should have `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" version="1.1">`
- Replace Panel section in korla/index.theme and korla-light/index.theme with:

```
########## Panel

[panel/16]
Context=Status
Size=16
Type=Fixed

[panel/22]
Context=Status
Size=22
Type=Fixes

[panel/24]
Context=Status
Size=24
Type=Fixes
```

If you have a text editor like Atom con you replace text in sgv files in 2 seconds. Just open a project to korla directory, make a search and replace with new text.

**Comment by bikass** [comment]
Yes I did tried this, but as I said then I get wrong icons even with scale 22x22. So I did not pushed changes and left as it was. I also tried to create separate folder, but as I wrote previously ir did not worked either. I will try again later.

**Comment by Digitalone1** [comment]
If you try to clone papirus from git and select it as your icon theme, do you see the same issue?

You could try to install a working theme and copy it's layout.

**Comment by bikass** [comment]
:) well it did worked. Las time I did not created 24 folder maybe that was a reason or that I called folder 16x16 - not 16. Ok so sizing issue solved. 
There is still issue with colors. But that thing is on other themes as well.
![Screenshot from 2019-03-10 17:43:47](https://user-images.githubusercontent.com/8824269/54087563-bb4dc880-435c-11e9-8ec0-3ded854b013d.png)
Now would be nice to add dpi scaling folders @2x

**Comment by Digitalone1** [comment]
Great, so size issue is gone. Which other theme has color issue?

**Comment by Digitalone1** [comment]
Should korla-light have it's own panel directory with black icons and korla the same directory with light ones?

**Comment by bikass** [comment]
Papirus and Paper have the same colour problems. No, the icons have ability to change colours(open .svg in text editor). And to make dark will not solve problem, because there are too many combinations how user will use theme (maybe light theme with dark panel...). I think, we can leave this as it is for now.

**Comment by Digitalone1** [comment]
So you think it's a Budgie issue?

Anyway, if it's good for you,  make a new release and I'll update on the AUR. 

This is a big update, maybe you can name it 1.0.

**Comment by bikass** [comment]
Same on xfce did not tested on gnome.

**Comment by Digitalone1** [comment]
Okay, maybe you can open an issue on Papirus and Paper git to see if they have some clue. You can close this or take it open for 2x folders...

**Comment by Digitalone1** [comment]
Invalid Type= "Fixes" line for icon theme:  "/usr/share/icons/korla/panel/22/" in terminal.

It's Type="Fixed"

**Comment by bikass** [comment]
Yes, I just copied your text without checking it :)
Thanks for fixing!

**Comment by Digitalone1** [comment]
My bad. Fixed now. :)
