### ISSUE TITLE
Remove kdeconnect icon in actions directory

### ISSUE THREAD

**Issue by Digitalone1** [bikass/korla#17]
kdeconnect icon in actions/scalable is quite simple and it replaces other kdeconnect icons in status, devices and apps directories.

If I remove actions/scalable/kdeconnect.svg, the icon shown in Dolphin and applications list is more beautiful, see Letv:
![Screenshot_20190310_220708](https://user-images.githubusercontent.com/25790525/54091555-a5063380-4381-11e9-9ab0-bff1b9ed8422.png)

Bikass, if you don't need it in actions folder, please remove it.

**Comment by bikass** [comment]
Ok, I removed it.
I see router share doesn't fit with other icons in kde. Can you check in "places" folder witch icon needs to be created. Maybe by duplicating and renaming some other icon?

**Comment by Digitalone1** [comment]
Don't worry, RouterShare seems good to me. Maybe Android icon could be same size as kdeconnect, but I don't know where to find it. Search for phone or Android in korla. It's not a big issue anyway.

**Comment by Digitalone1** [comment]
Found.

`korla/devices/scalable/multimedia-player.svg`
`korla/devices/scalable/multimedia-player-apple-ipod.svg`

It's a smartphone, but Plasma shows it as a multimedia player. Anyway, the icon is good, I'd like it same size as kdeconnect.

Check if `korla/devices/scalable/smartphone.svg`  and `korla/devices/scalable/phone.svg` have same size.

Thanks.

**Comment by bikass** [comment]
I resized icons check if they are ok now.

**Comment by Digitalone1** [comment]
That's OK.
