### ISSUE TITLE
Missing unmounted emblem

### ISSUE THREAD

**Issue by Digitalone1** [bikass/korla#18]
I noticed that unmounted-emblem of breeze theme is missing in korla. It's shown when I connect a device in a USB port.

![Screenshot_20190311_095119](https://user-images.githubusercontent.com/25790525/54112310-2a233400-43e6-11e9-8684-61d94122d6fe.png)

The icon is `breeze/emblems/22/emblem-unmounted.svg`.

![Screenshot_20190311_101823](https://user-images.githubusercontent.com/25790525/54112715-0dd3c700-43e7-11e9-851f-177fe6e8adcb.png)

**Comment by bikass** [comment]
Made this icon
