### ISSUE TITLE
Missing some Breeze emblems

### ISSUE THREAD

**Issue by Digitalone1** [bikass/korla#19]
Hello, in Dolphin I noticed that a Breeze emblem is showed when I select a folder/file.
This is a korla emblem when I place the mouse over a folder:
![Screenshot_20190317_092114](https://user-images.githubusercontent.com/25790525/54487548-99da6880-4897-11e9-88f6-6aaf177568fa.png)

But, when I select it, a Breeze emblem is showed:
![Screenshot_20190317_092206](https://user-images.githubusercontent.com/25790525/54487558-b70f3700-4897-11e9-8dd8-357320187f9b.png)

It's breeze/emblems/22/emblem-remove.svg
![Screenshot_20190317_092835](https://user-images.githubusercontent.com/25790525/54487564-c8f0da00-4897-11e9-9eba-cef85ff923e8.png)

Looking in Breeze emblems folder, I noticed that other emblems are missing.

![Screenshot_20190317_093555](https://user-images.githubusercontent.com/25790525/54487592-1cfbbe80-4898-11e9-9893-4a3b2faadc17.png)
breeze/emblems/22/emblem-information.svg

![Screenshot_20190317_093704](https://user-images.githubusercontent.com/25790525/54487597-3f8dd780-4898-11e9-9885-1ffe7f46bcd9.png)
breeze/emblems/22/emblem-mounted.svg

![Screenshot_20190317_093835](https://user-images.githubusercontent.com/25790525/54487625-76fc8400-4898-11e9-97e3-4b26403dd981.png)
breeze/emblems/22/emblem-pause.svg

![Screenshot_20190317_093939](https://user-images.githubusercontent.com/25790525/54487641-a7442280-4898-11e9-995c-c9ad0c2683ff.png)
breeze/emblems/22/emblem-question.svg

Could you draw them? Thanks.

![Screenshot_20190317_094316](https://user-images.githubusercontent.com/25790525/54487676-1de12000-4899-11e9-9859-42d9a8ee98fc.png)
breeze/emblems/22/emblem-warning.svg could be symlinked with breeze emblem-important

**Comment by bikass** [comment]
Hi, ok made those icons.

**Comment by Digitalone1** [comment]
Very beautiful bikass, thanks!
