### ISSUE TITLE
Invalid Type= "fixed" line for icon theme:  "/usr/share/icons/korla/places/symbolic/"

### ISSUE THREAD

**Issue by Digitalone1** [bikass/korla#2]
Hello, since the new release I see this warning on the command line repeated several times
`Invalid Type= "fixed" line for icon theme:  "/usr/share/icons/korla/places/symbolic/"`
Maybe because you wrote "fixed" starting with lowercase in index.theme. If you add me to the contributors, I'll try to fix on my own and you can release a new version.

Besides, I miss an icon in Dolphin. As you can see from the screenshot attached, Linux filesystem mounted devices in the left bar has Breeze icon. Do you know why? I think it should have same icon as "Basic Data Partition" (Windows partition) by your theme. That happened also with previous versions.

![screenshot_20181214_111719](https://user-images.githubusercontent.com/25790525/49997472-ffb20e00-ff91-11e8-8e9a-8a467c6bb516.png)

And do not forget to add license in the root directory (if you add me to the contributors, I'll do it).

Thanks.

**Comment by bikass** [comment]
Hi, it would be really nice if You could cover technical side of this theme. I've added You as contributor. 
I checked yesterday plasma on vm, many icons are not showing up. On Budgie those icons different (as you can see from screenshots). These in kde from "devices" and "places". This icon could be "drive-harddisk.svg". We need to find out naming for file system in kde. 
![screenshot from 2018-12-14 12 3a37 3a20](https://user-images.githubusercontent.com/8824269/49998612-64269a80-ff9d-11e8-876c-5b6421e9594c.png)
On Budgie ok with file system

**Comment by Digitalone1** [comment]
Changed to `Type=Fixed` and the warnings are gone.
I'll try to find the missing icon on my Dolphin.

**Comment by bikass** [comment]
Added icon but in devices/scalable . Does it work? But panel icons on plasma not from theme. How is on your side?

**Comment by Digitalone1** [comment]
Wait, there's a big problem. If I download the master zip and copy korla directory in `$HOME/.local/share/icons/` I can't see a lot of icons. That's because some of them has your ownership without permissions to read them fro other users.

Let's try fo fix this first. If you have them installed locally, please, give these commands. 
chmod 755 $(find "$HOME/.local/share/icons/" -type d)
chmod 644 $(find "$HOME/.local/share/icons/" -type f)

If there are no issues from command line, reupload korla folder.

**Comment by bikass** [comment]
I'm not sure if I did it right. I don't see any difference on plasma. What about new icons, I will add in future? Should I run same commands each time I add them?

**Comment by Digitalone1** [comment]
Permission is OK now, but I can't still access a lot of icons. It seems lots of symlink are missing. Do you see symlinks on your system?

For permissions, you don't have to run same command every time you add them, just make sure new files have the permission to be read by other users.

**Comment by Digitalone1** [comment]
Installed locally old 0.8.0 version and everithing works execpt type=fixed warnings.
Maybe you did something wrong in changing permissions and overwrote symlinks.

**Comment by Digitalone1** [comment]
I gave same commands on my system and symlinks are still there, so I don't know why they're missing after your last upload.

**Comment by bikass** [comment]
It's fine on my system all links are ok. But I cant push again, everything is up to date...

**Comment by Digitalone1** [comment]
Unfortunately no. It does not show. Even if I symlink drive-harddisk-root-symbolic.svg to drive-harddisk-symbolic.svg devices/symbolic.  :(

**Comment by bikass** [comment]
Must be some other nameing needed for this

**Comment by Digitalone1** [comment]
Yes, it's not `drive-harddisk-root-symbolic.svg`, but `drive-harddisk-root` to `drive-harddisk.svg` in scalable. You can delete `drive-harddisk-root-symbolic.svg` symlink.

**Comment by bikass** [comment]
Ok, I renamed symlink to drive-harddisk-root.svg.

**Comment by Digitalone1** [comment]
Another issue with 0.8.0 release. Bold icon on locked directories should not be like that in the screenshot, right? I don't remember it was like that in the previous releases.

![screenshot_20181214_145824](https://user-images.githubusercontent.com/25790525/50007425-2a5f8f00-ffb1-11e8-9c77-b769e0229cd5.png)

Don't care for Linux partition icon, I reverted to system-wide icons 0.8.0 version.

**Comment by Digitalone1** [comment]
Look another thing, /tmp icon is not korla's, noticed just now.

**Comment by bikass** [comment]
Yes, lock icon should be black gradient (on budgie is ok). Also plasma doesn't like svg with images, found some icons and fixing now. Well, need to hunt that "temp" now :)

**Comment by Digitalone1** [comment]
Do you know where are lock and /temp icons?

**Comment by bikass** [comment]
lock is in emblems/scalable not shure about tmp naming on Budie it shows up ok

**Comment by Digitalone1** [comment]
On Plasma should be something else. I'll look for...

**Comment by bikass** [comment]
Also "system settings" icon is incorrect in plasma. For me it shows as two gears. I guess it has different naming too

**Comment by Digitalone1** [comment]
`file:///usr/share/icons/breeze/places/64/folder-locked.svg`

**Comment by Digitalone1** [comment]
`file:///usr/share/icons/breeze/places/64/folder-temp.svg`

**Comment by Digitalone1** [comment]
`file:///usr/share/icons/breeze/apps/48/systemsettings.svg`

**Comment by bikass** [comment]
we have folder-locked.svg and systemsettings.svg. I made folder-temp.svg and emblem-locked.svg

**Comment by Digitalone1** [comment]
When you update, I'll check.
There are some other icons that needs to be fixed in systemsettings5

![screenshot_20181214_154705](https://user-images.githubusercontent.com/25790525/50009548-90e7ab80-ffb7-11e8-94c2-9242a92c531a.png)

Icons, keyboard shortcuts and others

**Comment by bikass** [comment]
ok, "icons" needs to be done. This icon with penguin is accessories-character-map, but there is another icon for shortcuts shortcuts.svg in apps/scalable (check if you like it). Which one is "others" icon?

**Comment by Digitalone1** [comment]
Lock is good. /temp icon is changed, but can you do it with a watch on it like in breeze?
apps/scalable/shortcuts.svg is good. Systemsettings application icon is not changed to me. 

I'm looking for icons in sysemsettings5...

**Comment by Digitalone1** [comment]
SystemSettings -> Icons: `file:///usr/share/icons/breeze/preferences/32/preferences-desktop-icons.svg`

**Comment by Digitalone1** [comment]
No, I don't think so.

SystemSettings -> Application Styles: `file:///usr/share/icons/breeze/preferences/32/preferences-desktop-theme.svg`
SystemSettings -> Login Settings: `file:///usr/share/icons/breeze/preferences/32/preferences-system-login.svg`

SystemSettings -> Application Styles -> GNOME Applications Style (GTK): `file:///usr/share/icons/breeze/preferences/32/gtkconfig.svg` and `file:///usr/share/icons/breeze/preferences/32/kde-gtk-config.svg`
SystemSettings -> Application Styles -> Windows Decorations: `file:///usr/share/icons/breeze/preferences/32/preferences-system-windows.svg`

**Comment by Digitalone1** [comment]
Maybe also a keyboard and joystick icons, if you can.

![screenshot_20181214_163739](https://user-images.githubusercontent.com/25790525/50012356-b4622480-ffbe-11e8-8669-b9c06c60779d.png)

**Comment by Digitalone1** [comment]
Keyboard: `file:///usr/share/icons/breeze/preferences/32/preferences-system-windows.svg`
Joystick: `file:///usr/share/icons/breeze/preferences/32/preferences-desktop-gaming.svg`, but maybe you already did that, so you don't need to do a new one.

**Comment by bikass** [comment]
Most icons were already made, but some were missing. I'm checking now. Joystick is in theme, but if you don't like I can make different

**Comment by Digitalone1** [comment]
If you already made it, don't worry, I thought Breeze has a joystick icon, but it's a game icon in realty (`preferences-desktop-gaming.svg`), so it's OK.

I supposed that some icons were already made, but they're not properly linked to match Breeze ones.

I see that network folder and server-database are missing, I'm searching for their location.

Thanks for your work.

**Comment by bikass** [comment]
Thank you! Now this icon theme is getting somewhere. But I'm curious about panel - like clock, network, are those still breeze icons on your system?

**Comment by Digitalone1** [comment]
Yes, on desktop panel they're always Breeze, I don't think you can change them, I don't know.

Check if these are present or needs to be done and customized like /temp folder:

`file:///usr/share/icons/breeze/places/64/folder-favorites.svg`
`file:///usr/share/icons/breeze/places/64/folder-activities.svg`
`file:///usr/share/icons/breeze/places/64/folder-bookmark.svg`
`file:///usr/share/icons/breeze/places/64/folder-cloud.svg`
`file:///usr/share/icons/breeze/places/64/folder-image.svg`
`file:///usr/share/icons/breeze/places/64/folder-images.svg`
`file:///usr/share/icons/breeze/places/64/folder-network.svg`
`file:///usr/share/icons/breeze/places/16/network-server-database.svg`
`file:///usr/share/icons/breeze/places/64/folder-onedrive.svg`
`file:///usr/share/icons/breeze/places/64/folder-pictures.svg`
`file:///usr/share/icons/breeze/places/64/folder-publicshare.svg`
`file:///usr/share/icons/breeze/places/64/folder-html.svg`
`file:///usr/share/icons/breeze/places/64/folder_html.svg`

**Comment by Digitalone1** [comment]
I'm going to try the new release. Anyway there's something new.

I noticed that qBittorrent icon changes in the system tray when I switch icon theme. This means icons on panel can be changed, but default icons can't because they are specific for that desktop theme. Breeze theme retrieves some icons directly from breeze folder not looking for them in other directories.

So changing icons on the panel requires breeze theme to be modified giving him specific icons rather than breeze ones.

**Comment by Digitalone1** [comment]
Great update, but some icons still missing in systemsettings. 

root directory misses preferences directory. I'll try to add it on my system and see what will happen.

**Comment by Digitalone1** [comment]
I made many symlinks from prefecences directory to original icons. I'll update it.

Please do 
`korla/apps/scalable/kde-gtk-config.svg` and `korla/apps/scalable/preferences-gtk-config.svg` with gnome icon inside, similar to `/usr/share/icons/breeze/preferences/32/preferences-gtk-config.svg`
`/usr/share/icons/breeze/preferences/32/plasma-search.svg` like `korla/apps/scalable/preferences-desktop-plasma.svg` with search icon inside
`/usr/share/icons/breeze/preferences/32/preferences-desktop-keyboard.svg` with a keyboard like in plasma
`/usr/share/icons/breeze/preferences/32/preferences-desktop-text-to-speech.svg` more similar to breeze version
`/usr/share/icons/breeze/preferences/32/preferences-web-browser-identification.svg` similar to breeze with fingerprint

Thanks.

**Comment by Digitalone1** [comment]
I uploaded symlinks through browser, but ended up to uploading original files. Don't know how to upload symlinks.

**Comment by bikass** [comment]
Hi, yes pushing via terminal too, didn't worked trough browser. Updated few icons.

**Comment by Digitalone1** [comment]
Please, if you want, `file:///usr/share/icons/korla/apps/scalable/accessories-character-map.svg` more similar at breeze, with a character of the keyboard, not the penguin.

**Comment by bikass** [comment]
Changed icon. Still left the penguin :)
No problems if you don't like some icons let me know.

**Comment by Digitalone1** [comment]
Beautiful! Thanks. ;)
This issue can be closed. I'll open another for reporting missing icons.
