### ISSUE TITLE
Bluetooth icon is almost invisible when disabled in a white panel

### ISSUE THREAD

**Issue by apandada1** [bikass/korla#20]
I am using Cinnamon with a white panel.
The bluetooth icon is almost invisible when it becomes inactive.

Possible solution: In Korla light (which, I presume, is for light-colored panels) use blue bluetooth icon (eg. `../korla/apps/scalable/bluetooth.svg`) when it is active and use a dark icon when it is inactive/disabled.
La Capitaine Icon Theme has different icons for light and dark panels. Something similar can be implemented.

**Comment by bikass** [comment]
Yes , there are issues with white panel at the moment. Some icons for some reason doesn't turn to dark like others.
