### ISSUE TITLE
Missing some Breeze icons

### ISSUE THREAD

**Issue by Digitalone1** [bikass/korla#21]
Hello, I discovered some missing icons.

I think `places/scalable/folder-ecrypted.svg` is wrong, correct name should be `folder-encrypted.svg`, but maybe in Budgie is right. I don't know. If it's wrong, rename it, or symlink if it's right because it doesn't match on Plasma.

`places/scalable/folder-visiting.svg` is corrupted, I can see it right only opening in Chromium. Can you fix it?
![Screenshot_20190331_111219](https://user-images.githubusercontent.com/25790525/55287181-e5b40400-53a5-11e9-9812-57b740be5dc3.png)

`breeze/emblems/8/emblem-unlocked.svg` (and symlink `breeze/emblems/8/emblem-encrypted-unlocked.svg`) are missing in korla. Can you draw it?
![Screenshot_20190331_113438](https://user-images.githubusercontent.com/25790525/55287434-09c51480-53a9-11e9-8196-c4f591678b4a.png)

Thanks.

**Comment by bikass** [comment]
Hi, I fixed those issues. Can you check if everything is ok?

**Comment by Digitalone1** [comment]
That's OK.

I found another one: `breeze/places/64/certificate-server.svg`
Can you please make a symlink `korla/places/scalable/certificate-server.svg` to `korla/places/scalable/folder-locked.svg`?

Then I'll push a new release for the AUR.

**Comment by Digitalone1** [comment]
Another little issue.

Shouldn't `korla/places/scalable/gnome-fs-directory-visiting.svg` be symlinked to `korla/places/scalable/folder-visiting.svg` rather than `folder.svg`?

**Comment by bikass** [comment]
Ok :) done
