### ISSUE TITLE
PulseEffects icon

### ISSUE THREAD

**Issue by Digitalone1** [bikass/korla#22]
Hello, can you improve PulseEffects icon?

The one you modified for korla is good, but I can't distinguish bars and circle buttons from background, especially since I use a light theme.

![Screenshot_20190405_123403](https://user-images.githubusercontent.com/25790525/55622202-d830bc80-579f-11e9-8a5a-f6edbad3d8b0.png)

Can you please change color for bar and/or circle buttons to highlight them? Thanks.

After this, I'll make a new release for the AUR.

**Comment by bikass** [comment]
Hi, it's strange because this icon has blue background. However, I did some cleanup for this icon. Check if it's ok on your side.

**Comment by Digitalone1** [comment]
So it was corrupted.
Now I see it correctly.
