### ISSUE TITLE
subtitle mimetype

### ISSUE THREAD

**Issue by Digitalone1** [bikass/korla#23]
Icon themes, not only korla, are missing various subtitle file icons.

Only subrip .srt file is specified, but there are also other subtitle format like 
```.ass .ssa. .vtt .smi .sami .smil .ssf```

For others a generic text icon is showed, but it's misleading.

So my idea is to change `mimetypes/scalable/application-x-subrip.svg` writing **sub** or **subtitle** rather than **srt**. After you upload the change, I will symlink other formats so all subtitles files have an icon with **sub**/**subtitle** showed upon it.

What do you think?

**Comment by bikass** [comment]
Hi, yes cool idea. 
Already changed the icon.

**Comment by Digitalone1** [comment]
Done. Thanks. In the next days I will update on the AUR.
