### ISSUE TITLE
Corrupted icons

### ISSUE THREAD

**Issue by Digitalone1** [bikass/korla#24]
The following icons are corrupted (can see them properly only opening with Chromium):

* `korla/places/scalable/folder-gdrive.svg`
* `korla/places/scalable/folder-image-people.svg`
* `korla/places/scalable/folder-linux.svg`
* `korla/places/scalable/folder-script.svg`

Besides, can you draw `korla/places/scalable/network-manager.svg` same style as other icons in places folder?

And please add `korla/places/scalable/folder-add.svg` (present in breeze icon theme), a folder with a plus (+) inside. And, only if you want, change `korla/places/scalable/folder-open.svg` (not really necessary, I don't know how it could be, maybe a folder with an arrow? Choose you...).

Thanks.

**Comment by bikass** [comment]
Hi, icons fixed.

**Comment by Digitalone1** [comment]
Thank you.
