### ISSUE TITLE
Icone da aggiungere

### ISSUE THREAD

**Issue by xzj8b3** [bikass/korla#25]
Splendido lavoro con ultimo aggiornamento,mi chiedevo però se potevi aggiungere icone di Devede-NG ,OphCrack,Conky, Conky-Manager e OpenJDK e SimpleScan

Stonano un pò ed è un peccato...Grazie in anticipo!!!

**Comment by bikass** [comment]
Hi I don't speak Italian. But I assume you requesting some icons to be added. All of them are in the theme except  OphCrack. However Conky and Conky-Manager icons were updated.

**Comment by Digitalone1** [comment]
@bikas yes he asked that. But maybe simple-scan is not symlinked to ʼorg.gnome.SimpleScanʼ? 

https://gitlab.gnome.org/GNOME/simple-scan/blob/master/data/simple-scan.desktop.in

@xjz8b3 ciao, per favore, scrivi in inglese qui.

**Comment by bikass** [comment]
org.gnome.SimpleScan is in theme, recently symlinked few of those org.gnome icons. I also made OphCrack icon.

**Comment by xzj8b3** [comment]
Hi. Yes, I meant Simple Scan.

I use Gnome Shell 3.32.2 on Fedora 30...I always liked your icons package
very much, I would only suggest a few additions or changes to make it even
more beautiful, for example:
Conky
Conky-Manager (if you succeed in a prettier icon for both)

It has to
Dvd95
OpenJDK
OphCrack
OnionShare
TimeShift
Telegram-Desktop
If it is not disturbing a slightly larger and less squared icon for "PDF"
displayed in the shell as a guide, or other

They are the most beautiful icons designed by you and so far is the most
beautiful package that there is compliments for the great work!!!





Seguimi su Facebook <https://www.facebook.com/IvanDeFelice>  Seguimi su
Twitter <https://twitter.com/ivan_toby>  Seguimi su Istagram
<https://www.instagram.com/ivan_e_toby/> Seguimi su Pinterest
<https://it.pinterest.com/Ivan_e_Toby/>




Il giorno sab 18 mag 2019 alle ore 10:04 bikass <notifications@github.com>
ha scritto:

**Comment by xzj8b3** [comment]
> org.gnome.SimpleScan is in theme, recently symlinked few of those org.gnome icons. I also made OphCrack icon.
Hi. Yes, I meant Simple Scan.

I use Gnome Shell 3.32.2 on Fedora 30...I always liked your icons package very much, I would only suggest a few additions or changes to make it even more beautiful, for example:
Conky
Conky-Manager (if you succeed in a prettier icon for both)

It has to
Dvd95
OpenJDK
OphCrack
OnionShare
TimeShift
Telegram-Desktop
If it is not disturbing a slightly larger and less squared icon for "PDF" displayed in the shell as a guide, or other

They are the most beautiful icons designed by you and so far is the most beautiful package that there is compliments for the great work!!!

**Comment by Digitalone1** [comment]
Is there a specific icon you are not seeing?
