### ISSUE TITLE
Korla Light - Missing icons

### ISSUE THREAD

**Issue by algent-al** [bikass/korla#26]
Wireless icons missing on panel:
![Wireless](https://user-images.githubusercontent.com/46356616/57956365-035b0f80-78f9-11e9-8bfc-b585789e5201.png)

Missing application icon on Korla Theme.
Screenshot and Terminal
![Terminal+Screenshot](https://user-images.githubusercontent.com/46356616/57956451-40bf9d00-78f9-11e9-953f-5b80a39867e7.png)

Maybe there are others, but these were on my panel. These missing icons are only in "Korla Light", "Korla" is better.

System: Solus Budgie 4.0

**Comment by bikass** [comment]
My main system is Solus. And light theme works fine. Did you tried to update cache or logout-login?

**Comment by algent-al** [comment]
I even restarted PC. And still same result. I have installed this theme on `$HOME/.icons` maybe this is why the Folder Links from "korla" are not working on "korla-light". Probably "korla-light" should be Independent icon theme, without any link for other folders.

**Comment by bikass** [comment]
It should work in $Home directory.
"Korla" and "Korla-light" should be together. If you copying just light - it won't work. I have no idea why it's not working. Can you try download and extract again?

**Comment by algent-al** [comment]
Yes I downloaded it again, and with same results. I will try it in another PC, maybe the problem is in my PC.

**Comment by Digitalone1** [comment]
Hello, `$HOME/.icons` is not the right place, it could also work but that directory is not the default for icon themes. The exact folders are listed [here](https://github.com/bikass/korla#installation) and korla and korla-light should be installed together because light-theme depends on korla.  

If you have Arch Linux, you can install [AUR package](https://aur.archlinux.org/packages/korla-icon-theme) that simplifies this things and themes are available system-wide.

**Comment by algent-al** [comment]
I don't know why it works for you, but still not working for me. I tried this again on another PC with Virtual Box, and I have same results. Installed again on $HOME and "korla-light" icons from symbolic link folders are not loaded. 
For me only "korla" is fine and it is my favourite icon theme so far.
I don't use "korla-light", just wanted to report the issue.

> Hello, $HOME/.icons is not the right place

Then you have to clarify this on README which it is:

```
and copy both korla and korla-light subfolders to one of the following folders:
    /usr/share/icons/ - icons available system-wide
    $HOME/.local/share/icons/ - icons only available to local user
```
That "korla-light" will not work on   
`$HOME/.local/share/icons/`

**Comment by Digitalone1** [comment]
Maybe you don't understood properly.

`$HOME/.icons` and `$HOME/.local/share/icons/` are two **different** places.

I don't know where you placed them, but if you do it in the second (`$HOME/.local/share/icons/`), it will work. 

Please, copy here the absolute path of one or your icon. Just to make sure where they are placed. 

Take in consideration that `$HOME` is a variable, it contains your local folder, so the absolute path should be `/home/yourusername/.local/share/icons/`.

Can you specify which Linux distribution and what desktop environment are you using?

You can also copy korla and korla-light inside `/usr/share/icons/` using **sudo** from command line.

**Comment by algent-al** [comment]
In both locatins `$HOME/.icons` and` $HOME/.local/share/icons/` I have same results.
My system is Solus Budgie 4.0.

 Yes in `/usr/share/icons/ ` korla-light works fine.

**Comment by Digitalone1** [comment]
I have them in `/usr/share/icons` and it works. Tested days ago in `$HOME/.local/share/icons/` and it worked too. Maybe I will test in the next hours too and let you know.

**Comment by Digitalone1** [comment]
@algent-al I removed it from /usr/share and placed in `$HOME/.local/share/icons/`, it's working to me.

I have Plasma 5 Desktop, maybe it's something wrong with Budgie, I don't know.

Can you replace it under `$HOME/.local/share/icons/` and copy here the absolute path of an icon? Thanks.

**Comment by bikass** [comment]
I have Solus and Ubuntu with Budgie.  And on both systems icons are placed in $HOME/.local/share/icons/
Both works fine.

**Comment by algent-al** [comment]
> Can you replace it under $HOME/.local/share/icons/ and copy here the absolute path of an icon? 

`/home/algent/.local/share/icons/korla-light/categories/scalable@2`
`/home/algent/.local/share/icons/korla-light/categories/scalable`
Is this what you mean?

**Comment by algent-al** [comment]
I think i found the problem and now the korla-light is working with all it's icons.
I deleted every folder and subfolder with @2 inside korla-light.

![korla-light-@2](https://user-images.githubusercontent.com/46356616/58039616-88316d80-7b33-11e9-9ea0-eb2186197d44.png)

**Comment by Digitalone1** [comment]
Do you have an HiDPI monitor?

Maybe it's a wrong configuration for HiDPI folders, but I can't test it on my monitor.

**Comment by algent-al** [comment]
I don't think so. I have an old "NEC AccuSync LCD92VM 19" LCD Monitor" from 2005. 
I am sorry I didn't thought that the problem was with my monitor. Probably that is why those icons with HiDPI didn't work, only by deleting those folder made the icon theme to work.

**Comment by Digitalone1** [comment]
Please post the outupt of the following commands

```
xdpyinfo | grep -B 2 resolution
xrandr | grep -w connected
```

**Comment by algent-al** [comment]
```
xdpyinfo | grep -B 2 resolution
screen #0:
  dimensions:    1280x1024 pixels (338x270 millimeters)
  resolution:    96x96 dots per inch
```
```
xrandr | grep -w connected
VGA1 connected primary 1280x1024+0+0 (normal left inverted right x axis y axis) 380mm x 300mm
```

**Comment by Digitalone1** [comment]
Your DPI is 96, same as mine, so it's not an issue related to HiDPI folders (if so, it wouldn't work inside /usr/share neither). There should be something wrong with your configuration.

How do you install them? Do you clone from the command line or download the release zip?

**Comment by algent-al** [comment]
> How do you install them? Do you clone from the command line or download the release zip?

It doesn't matter I tried them both.

Tried this on Virtual Box on a  host machine with quite new hardware. 
```
algent@fujitsu ~ $ xdpyinfo | grep -B 2 resolution
screen #0:
  dimensions:    1920x976 pixels (508x258 millimeters)
  resolution:    96x96 dots per inch
algent@fujitsu ~ $ xrandr | grep -w connected
VGA-1 connected primary 1920x976+0+0 (normal left inverted right x axis y axis) 0mm x 0mm
```

It is strange but I found that the problem is only with the folder animations@2. After deleted korla-light theme start working, even if I restore later animations@2, the theme is still working. Tried logging in/out and restarting PC. Same results on `$HOME/.icons `and `$HOME/.local/share/icons`.

So the fix is just delete and restore only **animations@2** folder. It doesn't matter if you delete it before or afte switching to the theme.

**Comment by bikass** [comment]
Well I tried today on ubuntu budgie and yes light theme was wrong. I updated icon caches on both themes, did that chmod 644 and 755. That fixed light theme and some icons after restart. 
@algent-al can you test if everything is ok (download from latest commits)?

**Comment by algent-al** [comment]
Right now I am at work PC. I tried this on VB, and yes the new commit is working out of the box. I think it is fixed.

**Comment by Digitalone1** [comment]
> Well I tried today on ubuntu budgie and yes light theme was wrong. I updated icon caches on both themes, did that chmod 644 and 755. That fixed light theme and some icons after restart.
> @algent-al can you test if everything is ok (download from latest commits)?

If it was an icon cache problem, he could resolve it executing the scripts included in the git. I didn't think about that.

I had issues related to permission in the past, how did you change the permission and which files you did it on? HiDPI folders are simply simlinks, so I don't think there's a permission issue on them.

**Comment by bikass** [comment]
Yes maybe it's just cache. But in case I just ran these two lines you gave me few months ago:
chmod 644 $(find "$HOME/.local/share/icons/" -type f)
chmod 755 $(find "$HOME/.local/share/icons/" -type d)

But I think there is still some issues with index. Some icons are too big ... sometimes...
![Screenshot from 2019-05-21 11:41:30](https://user-images.githubusercontent.com/8824269/58085843-2837d700-7bc6-11e9-89eb-a172f35528d9.png)
I updated cache, restarted and icons were ok. After few hours started laptop and icons were big again. Updated cache, restart - good again...

**Comment by Digitalone1** [comment]
> Yes maybe it's just cache. But in case I just ran these two lines you gave me few months ago:
> chmod 644 $(find "$HOME/.local/share/icons/" -type f)
> chmod 755 $(find "$HOME/.local/share/icons/" -type d)
> 
> But I think there is still some issues with index. Some icons are too big ... sometimes...
> I updated cache, restarted and icons were ok. After few hours started laptop and icons were big again. Updated cache, restart - good again...

If permission was changed, we should see it in the commit. I don't see permission changes in the last commit, so I think it's only a cache issue.

I don't have problems on Plasma, but as far as I know Plasma has its own cache method, it don't rely on `icon-theme.cache`.

If you need to cache regularly, you could write a bash script executed at every startup:

```
#!/bin/bash

gtk-update-icon-cache -f /absolute/path/to/icon/folder 
``` 

placed in `~/.config/autostart/`.

Anyway, do you need to add some other icons or fix to the repository? If not, I will push a new release for the AUR package.

**Comment by bikass** [comment]
All is done at the moment. You can push it.

**Comment by algent-al** [comment]
I think you can close the issue. On my end everything is OK. Thank you for you help. I also learned a few things here.
