### ISSUE TITLE
Some new icons and fix

### ISSUE THREAD

**Issue by Digitalone1** [bikass/korla#27]
Hello @bikass 

I'd like to add brave-browser icon, but I don't like la capitaine version, could you redesign it from the following?
https://github.com/brave/brave-browser/blob/master/docs/source/_static/brave-release.svg

It's already svg, but width/height is not 48px. Is it enough to change `width="48" height="48"` or should be changed path tag also?

Besides, take a look at this:
https://github.com/keeferrourke/la-capitaine-icon-theme/commit/5af554f3fd9b9e149be5c7349f6396125ba2a56c?short_path=a2b8a1a#diff-a2b8a1ab2fc7915a1ad3c2c274551efe

Do you like the redesigned anki icon or the old one? 

And I'd like to change `apps/scalable/atom.svg` to the following one:
https://commons.wikimedia.org/wiki/File:Icon_Atom.svg

Because the current one is too generic and atom icon inside is too little, I can't see it on the dock.
And `apps/scalable/atom-beta.svg` the same with a beta in the corner.

What do you think?

**Comment by Digitalone1** [comment]
Thanks @bikass , you added them, but atom and brave are not 48x48, is it okay?

**Comment by Digitalone1** [comment]
@bikass meanwhile I made a new commit with symlinks for brave icons

**Comment by bikass** [comment]
Thanks! 
Scaled icons to 48x48

**Comment by Digitalone1** [comment]
Thanks to you.
