### ISSUE TITLE
Network place and pdf icons

### ISSUE THREAD

**Issue by Digitalone1** [bikass/korla#28]
Hello, I wonder why [network place](https://github.com/bikass/korla/blob/master/korla/places/scalable/network-manager.svg) icons have a different style compared to the other [ones](https://github.com/bikass/korla/blob/master/korla/places/scalable/folder-add.svg).

Maybe because network-manager is used for an app icon? If not, could it be done the same as others?

And pdf icons like [acroread](https://github.com/bikass/korla/blob/master/korla/apps/scalable/acroread.svg) and [pdfchain](https://github.com/bikass/korla/blob/master/korla/apps/scalable/pdfchain.svg) are good with the "A" cursive, but I think they should also have a PDF description. Something like [this](https://upload.wikimedia.org/wikipedia/commons/8/87/PDF_file_icon.svg).

What do you think?

**Comment by bikass** [comment]
Hi, yes "network place" icon is wrong. I fixed that and added "PDF" to icons.

**Comment by Digitalone1** [comment]
Beautiful. Thanks.
