### ISSUE TITLE
v.1.1.1 Packaging Error

### ISSUE THREAD

**Issue by algent-al** [bikass/korla#29]
Hi, I am trying to package this icon theme for Solus (just for my fun), but i am receiving this error:

This happens with last version v1.1.1
`[Errno 2] No such file or directory: '/home/build/YPKG/root/korla-icon-theme/install/usr/share/icons/korla/apps/scalable/application-x-pml18.svg'`

Didn't had any problem with v1.1.0. Just tested it and was builded fine.

**Comment by bikass** [comment]
Hi, yesterday I was fixing some icons and this icon was one of them. I made new release can you check if its ok now.
But is strange that there was no problem before.

**Comment by algent-al** [comment]
No. Unfortunally i get same error with same file. `application-x-pml18.svg`.

**Comment by bikass** [comment]
This icon is symlink to freeoffice-planmaker.svg I'm out of ideas what is wrong. You can try yourself to remake this symlink or delete icon and check if there is no other issues?

**Comment by bikass** [comment]
I remade symlinks of freeoffice icons. It's in latest commits.

**Comment by algent-al** [comment]
Closing the issue because, I think that the problem is in the Solus itselt with its packaging system.

**Comment by algent-al** [comment]
It is interesting that v.1.1.3 was builded successfully. While v.1.1.2 and v.1.1.1 can't.
Thank you for the fix.
