### ISSUE TITLE
Changing or missing icons

### ISSUE THREAD

**Issue by Digitalone1** [bikass/korla#3]
Missing:
`file:///usr/share/icons/breeze/apps/48/preferences-desktop-font-installer.svg`
`file:///usr/share/icons/breeze/places/64/folder-blue.svg`
`file:///usr/share/icons/breeze/places/64/folder-cyan.svg`
`file:///usr/share/icons/breeze/places/64/folder-decrypted.svg`
`file:///usr/share/icons/breeze/places/64/folder-development.svg`
`file:///usr/share/icons/breeze/places/64/folder-encrypted.svg`
`file:///usr/share/icons/breeze/places/64/folder-gdrive.svg`
`file:///usr/share/icons/breeze/places/64/folder-image-people.svg`
`file:///usr/share/icons/breeze/places/64/folder-root.svg`

Missing mimetypes
`file:///usr/share/icons/breeze/mimetypes/64/application-vnd.appimage.svg`
`file:///usr/share/icons/breeze/mimetypes/64/application-vnd.ms-excel.addin.macroenabled.12.svg`
`file:///usr/share/icons/breeze/mimetypes/64/application-vnd.ms-powerpoint.addin.macroenabled.12.svg`
`file:///usr/share/icons/breeze/mimetypes/64/application-vnd.ms-infopath.svg`
`file:///usr/share/icons/breeze/mimetypes/32/application-vnd.ms-powerpoint.slide.macroenabled.12.svg`
`file:///usr/share/icons/breeze/mimetypes/64/application-vnd.ms-powerpoint.slideshow.macroenabled.12.svg`
`file:///usr/share/icons/breeze/mimetypes/64/application-vnd.ms-publisher.svg`
`file:///usr/share/icons/breeze/mimetypes/64/application-vnd.nintendo.snes.rom.svg`
`file:///usr/share/icons/breeze/mimetypes/64/application-vnd.visio.svg`
`file:///usr/share/icons/breeze/mimetypes/64/application-x-chm.svg`
`file:///usr/share/icons/breeze/mimetypes/64/application-x-gzpostscript.svg`
`file:///usr/share/icons/breeze/mimetypes/64/application-x-kdenlivetitle.svg`
`file:///usr/share/icons/breeze/mimetypes/64/application-x-kexi-connectiondata.svg`
`file:///usr/share/icons/breeze/mimetypes/64/application-x-kexiproject-shortcut.svg`
`file:///usr/share/icons/breeze/mimetypes/64/application-x-kplato.svg`
`file:///usr/share/icons/breeze/mimetypes/64/application-x-kvtml.svg`
`file:///usr/share/icons/breeze/mimetypes/64/application-x-macbinary.svg`
`file:///usr/share/icons/breeze/mimetypes/64/application-x-ms-shortcut.svg`
`file:///usr/share/icons/breeze/mimetypes/64/application-x-plasma.svg`
`file:///usr/share/icons/breeze/mimetypes/64/application-x-skgc.svg`
`file:///usr/share/icons/breeze/mimetypes/64/application-x-skg.svg`
`file:///usr/share/icons/breeze/mimetypes/64/application-x-xliff.svg`
`file:///usr/share/icons/breeze/mimetypes/64/application-xmind.svg`
`file:///usr/share/icons/breeze/mimetypes/64/image-vnd.dgn.svg`
`file:///usr/share/icons/breeze/mimetypes/64/image-vnd.djvu.svg`
`file:///usr/share/icons/breeze/mimetypes/64/image-vnd.dwg.svg`
`file:///usr/share/icons/breeze/mimetypes/64/image-x-vnd.trolltech.qpicture.svg`
`file:///usr/share/icons/breeze/mimetypes/64/text-dockerfile.svg`
`file:///usr/share/icons/breeze/mimetypes/64/text-rtf.svg`
`file:///usr/share/icons/breeze/mimetypes/64/text-x-adasrc.svg`
`file:///usr/share/icons/breeze/mimetypes/64/text-x-apport.svg`
`file:///usr/share/icons/breeze/mimetypes/64/text-x-go.svg`
`file:///usr/share/icons/breeze/mimetypes/64/text-x-haskell.svg`
`file:///usr/share/icons/breeze/mimetypes/64/text-x-hex.svg`
`file:///usr/share/icons/breeze/mimetypes/64/text-x-po.svg`
`file:///usr/share/icons/breeze/mimetypes/64/text-x-qml.svg`
`file:///usr/share/icons/breeze/mimetypes/64/virtualbox-hdd.svg`
`file:///usr/share/icons/breeze/mimetypes/64/virtualbox-ova.svg`
`file:///usr/share/icons/breeze/mimetypes/64/virtualbox-ovf.svg`
`file:///usr/share/icons/breeze/mimetypes/64/virtualbox-vbox-extpack.svg`
`file:///usr/share/icons/breeze/mimetypes/64/virtualbox-vbox.svg`
`file:///usr/share/icons/breeze/mimetypes/64/virtualbox-vdi.svg`
`file:///usr/share/icons/breeze/mimetypes/64/virtualbox-vmdk.svg`
`file:///usr/share/icons/breeze/mimetypes/64/x-media-podcast.svg`
`file:///usr/share/icons/breeze/mimetypes/64/x-office-address-book.svg`
`file:///usr/share/icons/breeze/mimetypes/64/x-office-calendar.svg`

**Comment by Digitalone1** [comment]
Missing in /actions/symbolic:
`file:///usr/share/icons/breeze/actions/symbolic/bookmark-add-symbolic.svg`
`file:///usr/share/icons/breeze/actions/symbolic/change-date-symbolic.svg`
`file:///usr/share/icons/breeze/actions/symbolic/color-profile.svg`
`file:///usr/share/icons/breeze/actions/symbolic/comment-symbolic.svg`
`file:///usr/share/icons/breeze/actions/symbolic/content-loading-symbolic.svg`
`file:///usr/share/icons/breeze/actions/symbolic/document-edit-symbolic.svg`
`file:///usr/share/icons/breeze/actions/symbolic/edit-clear-rtl-symbolic.svg`
`file:///usr/share/icons/breeze/actions/symbolic/export-symbolic.svg`
`file:///usr/share/icons/breeze/actions/symbolic/extension-symbolic.svg`
`file:///usr/share/icons/breeze/actions/symbolic/file-catalog-symbolic.svg`
`file:///usr/share/icons/breeze/actions/symbolic/file-library-symbolic.svg`
`file:///usr/share/icons/breeze/actions/symbolic/file-search-symbolic.svg`
`file:///usr/share/icons/breeze/actions/symbolic/filter-symbolic.svg`
`file:///usr/share/icons/breeze/actions/symbolic/find-location-symbolic.svg`
`file:///usr/share/icons/breeze/actions/symbolic/histogram-symbolic.svg`
`file:///usr/share/icons/breeze/actions/symbolic/image-flip-horizontal-symbolic.svg`
`file:///usr/share/icons/breeze/actions/symbolic/image-flip-vertical-symbolic.svg`
`file:///usr/share/icons/breeze/actions/symbolic/image-invert-symbolic.svg`
`file:///usr/share/icons/breeze/actions/symbolic/image-navigator-symbolic.svg`
`file:///usr/share/icons/breeze/actions/symbolic/image-resize-symbolic.svg`
`file:///usr/share/icons/breeze/actions/symbolic/image-rotate-left-symbolic.svg`
`file:///usr/share/icons/breeze/actions/symbolic/image-rotate-right-symbolic.svg`
`file:///usr/share/icons/breeze/actions/symbolic/image-rotate-symbolic.svg`
`file:///usr/share/icons/breeze/actions/symbolic/map-symbolic.svg`
`file:///usr/share/icons/breeze/actions/symbolic/media-eject-symbolic.svg`
`file:///usr/share/icons/breeze/actions/symbolic/palette-symbolic.svg`
`file:///usr/share/icons/breeze/actions/symbolic/special-effects-symbolic.svg`
`file:///usr/share/icons/breeze/actions/symbolic/tools-symbolic.svg`
`file:///usr/share/icons/breeze/actions/symbolic/view-presentation-symbolic.svg`
`file:///usr/share/icons/breeze/actions/symbolic/view-zoom-fit-height-symbolic.svg`
`file:///usr/share/icons/breeze/actions/symbolic/view-zoom-fit-symbolic.svg`
`file:///usr/share/icons/breeze/actions/symbolic/view-zoom-fit-width-symbolic.svg`
`file:///usr/share/icons/breeze/actions/symbolic/view-zoom-in-symbolic.svg`
`file:///usr/share/icons/breeze/actions/symbolic/view-zoom-original-symbolic.svg`
`file:///usr/share/icons/breeze/actions/symbolic/view-zoom-out-symbolic.svg`

Propose to change:
`file:///home/giuseppe/.local/share/icons/korla/actions/symbolic/contact-new-symbolic.svg` add a plus meaning to add a contact
`/korla/actions/symbolic/edit-clear-symbolic-rtl.svg` change direction like in plasma

Preview icon changed color. It don't fit well in my Dolphin. Do you use a dark theme and need it light?
![screenshot_20181216_154922](https://user-images.githubusercontent.com/25790525/50055138-de485200-014a-11e9-96ef-18b4956240d0.png)

**Comment by bikass** [comment]
Try to download latest, I fixed that today.

**Comment by Digitalone1** [comment]
> Try to download latest, I fixed that today.

You're right, thanks.

**Comment by bikass** [comment]
I started to check /actions/symbolic most of them linked to /actions/16 . And in Korla most icons are in actions/scalabe just symlinks needs to be created. So I will skip these and will start mimetypes.

**Comment by Digitalone1** [comment]
That's good, maybe I'll make the symlinks when I have time.

**Comment by Digitalone1** [comment]
Added/fixed missing action-symbolic icons and symlinks where needed.

I think those:
'file:///home/giuseppe/Desktop/korla/korla/actions/scalable/system-run.svg'
'file:///home/giuseppe/Desktop/korla/korla/actions/symbolic/system-run-symbolic.svg'
should be similar to breeze being "system run" and not "system settings".

**Comment by bikass** [comment]
Thanks! I check later. But now I see broken links in actions/symbolic (call-end-symbolic.svg, color-profile.svg ...) . Do you do ln - sr  command, or just ln -s ?

**Comment by Digitalone1** [comment]
I copied some symlinks from breeze to korla, they had relative path, so they should be

**Comment by Digitalone1** [comment]
I copied some symlinks from breeze to korla, they had relative path, so they should be okay. I'll check and fix, if necessary, don't worry.

**Comment by Digitalone1** [comment]
You were right, there were absolute paths, fixed now.

**Comment by Digitalone1** [comment]
Added some mimetypes. Other icons are minor importance, we can skip for now. 
If you have something else to add, do it or I'll make another release to update AUR package since actual release has some corrupted icons.

**Comment by Digitalone1** [comment]
This can be closed, we can focus later on other missing icons.
