### ISSUE TITLE
[Request Missing Icons]

### ISSUE THREAD

**Issue by btd1337** [bikass/korla#30]
- [x] **Adobe Photoshop CS6**
Comment=PlayOnLinux
Icon=AdobePhotoshop
[Icon Link](https://www.iconfinder.com/icons/1785889/adobe_cloud_creative_editor_graphics_photoshop_raster_icon)

- [x] **balenaEtcher**
Comment=Flash OS images to SD cards and USB drives, safely and easily.
Icon=balena-etcher-electron
[Icon Link](https://github.com/balena-io/etcher/blob/master/assets/icon.png)

- [x] **Code - OSS**
Comment=Visual Studio Code Open Source Edition.
Icon=code-oss
[Icon Link]()

- [x] **Sequeler**
Comment=Friendly SQL Client
Icon=com.github.alecaddd.sequeler
[Icon Link](https://github.com/Alecaddd/sequeler/blob/master/data/assets/icons/128x128/com.github.alecaddd.sequeler.svg)

- [x] **Taxi**
Comment=Transfer local and remotes files
Icon=com.github.alecaddd.taxi
[Icon Link](https://github.com/Alecaddd/taxi/blob/master/data/icons/128.svg)

- [x] **Gitignore**
Comment=Gitignore reference for various languages
Icon=com.github.arshubham.gitignore
[Icon Link](https://github.com/arshubham/gitignore/blob/master/data/images/icons/128/com.github.arshubham.gitignore.svg)

- [x] **Hash It**
Comment=Generate and verify file hashes
Icon=com.github.artemanufrij.hashit
[Icon Link](https://github.com/artemanufrij/hashit/blob/master/data/icons/64/com.github.artemanufrij.hashit.svg)

- [x] **Image Burner**
Comment=Burn images to devices
Icon=com.github.artemanufrij.imageburner
[Icon Link](https://github.com/artemanufrij/imageburner/blob/master/data/icons/com.github.artemanufrij.imageburner.svg)

- [x] **Screencast**
Comment=Record your screen
Icon=com.github.artemanufrij.screencast
[Icon Link](https://github.com/artemanufrij/screencast/blob/master/data/icons/128/com.github.artemanufrij.screencast.svg)

- [x] **Bookworm**
Comment=Read and manage eBooks
Icon=com.github.babluboy.bookworm
[Icon Link](https://github.com/babluboy/bookworm/blob/master/data/icons/128/com.github.babluboy.bookworm.svg)

- [x] **Vala Tester**
Comment=Test some Vala code!
Icon=com.github.bartzaalberg.vala-tester
[Icon Link](https://github.com/bartzaalberg/vala-tester/blob/master/data/icons/128/com.github.bartzaalberg.vala-tester.svg)

- [x] **ValaCompiler**
Comment=A simple GUI for valac
Icon=com.github.basjam.valacompiler
[Icon Link](https://github.com/basjam/ValaCompiler/blob/master/data/icons/128/com.github.basjam.valacompiler.svg)

- [x] **VServer**
Comment=Open an http server in the selected folder and share your files.
Icon=com.github.bcedu.valasimplehttpserver
[Icon Link](https://github.com/bcedu/ValaSimpleHTTPServer/blob/master/data/icons/com.github.bcedu.valasimplehttpserver.svg)

- [x] **Copy Paste Grab**
Comment=Download videos from hundreds of websites
Icon=com.github.cryptowyrm.copypastegrab
[Icon Link](https://github.com/cryptowyrm/copypastegrab/blob/master/data/icons/128/com.github.cryptowyrm.copypastegrab.svg)

- [x] **Formatter**
Comment=Format devices
Icon=com.github.djaler.formatter
[Icon Link](https://github.com/Djaler/Formatter/blob/master/data/icons/com.github.djaler.formatter.svg)

- [x] **EasySSH**
Comment=Manage your ssh connections
Icon=com.github.muriloventuroso.easyssh
[Icon Link](https://github.com/muriloventuroso/easyssh/blob/master/data/icons/128/com.github.muriloventuroso.easyssh.svg)

- [x] **Resizer**
Comment=Image resizer
Icon=com.github.peteruithoven.resizer
[Icon Link](https://github.com/peteruithoven/resizer/blob/master/data/icons/128.svg)

- [x] **Minder**
Comment=Create, develop and visualize your ideas
Icon=com.github.phase1geo.minder
[Icon Link](https://github.com/phase1geo/Minder/blob/master/data/icons/128/com.github.phase1geo.minder.svg)

- [x] **Notes-Up**
Comment=Your markdown notebook
Icon=com.github.philip-scott.notes-up
[Icon Link](https://github.com/Philip-Scott/Notes-up/blob/master/data/icons/64/com.github.philip-scott.notes-up.svg)

- [x] **Spice-Up**
Comment=Spice up your slides
Icon=com.github.philip-scott.spice-up
[Icon Link](https://github.com/aljelly/Spice-up/blob/new-icons/data/icons/64/com.github.philip-scott.spice-up.svg)

- [x] **Raddiu**
Comment=Listen to web radios
Icon=com.github.ranfdev.raddiu
[Icon Link](https://github.com/ranfdev/raddiu/blob/master/data/icons/128/com.github.ranfdev.raddiu.svg)

- [x] **Mindi**
Comment=A simple Video to Audio converter
Icon=com.github.torikulhabib.mindi
[Icon Link](https://github.com/torikulhabib/mindi/blob/master/data/icons/128.svg)

- [x] **Spectator**
Comment=REST Client
Icon=com.github.treagod.spectator
[Icon Link](https://github.com/treagod/spectator/blob/master/data/icons/128x128/com.github.treagod.spectator.svg)

- [x] **TeamViewer 14**
Comment=Remote control and meeting solution.
Icon=TeamViewer
[Icon Link]()

- [x] **EDuke32**
Comment=Advanced Duke Nukem 3D engine
Icon=eduke32
[Icon Link](https://i.imgur.com/xdi3t44.png)

- [x] **EmulationStation**
Comment=Emulationstation
Icon=emulationstation
[Icon Link](https://digimoot.files.wordpress.com/2018/08/retropie-setup-ubuntu-or-mint1.png)

- [x] **GdaBrowser**
Comment=Browse your database's contents
Icon=gda-browser-5.0
[Icon Link](http://www.iconarchive.com/show/papirus-apps-icons-by-papirus-team/gda-browser-5.0-icon.html)

- [x] **Gda Control Center**
Comment=Configure your database access environment
Icon=gda-control-center
[Icon Link](https://c7.uihere.com/files/294/418/482/database-administrator-computer-icons-clip-art-maintenance-equipment-thumb.jpg)

- [x] **Git Cola**
Comment=The highly caffeinated Git GUI
Icon=git-cola
[Icon Link](https://snapforum.s3.amazonaws.com/original/2X/5/5b3a5c8cb7c821d12ebf30ebc91bdec80726ada8.png)

- [x] **Thunderbolt**
Comment=Manage Thunderbolt devices
Icon=thunderbolt
[Icon Link](https://gitlab.freedesktop.org/uploads/-/system/project/avatar/32/thunderbolt-symbolic.png?width=40)

- [x] **Granite Demo**
Comment=A demo of the Granite toolkit
Icon=applications-interfacedesign
[Icon Link]()

- [x] **GTK+ Demo**
Comment=GTK+ code examples and demonstrations
Icon=gtk3-demo
[Icon Link](http://www.iconarchive.com/show/papirus-apps-icons-by-papirus-team/gtk3-demo-icon.html)

- [x] **Icon Browser**
Comment=An application that shows themed icons
Icon=gtk3-icon-browser
[Icon Link]()

- [x] **Widget Factory**
Comment=A showcase for GTK+ widgets, designed for testing themes.
Icon=gtk3-widget-factory
[Icon Link]()

- [x] **OpenJDK Java 10 Runtime**
Comment=OpenJDK Java 10 Runtime
Icon=java10-openjdk
[Icon Link]()

- [x] **Klavaro**
Comment=A very flexible and efficient touch typing tutor.
Icon=klavaro
[Icon Link](https://github.com/cbrnix/Newaita/blob/master/Newaita/apps/64/klavaro.svg)

- [x] **Koala**
Comment=A cool tool for web developers
Icon=koala
[Icon Link](https://github.com/oklai/koala/blob/master/assets-linux/icons/hicolor/128x128/apps/koala.png)

- [x] **Devhelp**
Comment=A developer tool for browsing and searching API documentation
Icon=org.gnome.Devhelp
[Icon Link]()

- [x] **Pomodoro**
Comment=A simple time management utility
Icon=gnome-pomodoro
[Icon Link](http://gnomepomodoro.org/images/icons/256x256.png)

- [x] **Sound Recorder**
Comment=Record sound via the microphone and play it back
Icon=org.gnome.SoundRecorder
[Icon Link]()

- [x] **pCloud**
Comment=pCloud Drive Client built using electron and node.js. Distributed with AppImage.
Icon=pcloud
[Icon Link](https://icons8.com.br/icon/91483/pcloud)

- [x] **PCSX2**
Comment=Sony Playstation 2 emulator
Icon=PCSX2
[Icon Link]()

- [x] **pgAdmin 4**
Comment=PostgreSQL Tools
Icon=pgAdmin4
[Icon Link]()

- [x] **QEMU**
Icon=qemu
[Icon Link](https://qemu.weilnetz.de/icon/benoit/black_and_orange_qemu_head-128x128.png)

- [x] **Qt V4L2 video capture utility**
Comment=Viewer for video capture
Icon=qvidcap
[Icon Link]()

- [x] **Robo 3T**
Comment=Shell-centric MongoDB management tool
Icon=robo3t
[Icon Link](https://raw.githubusercontent.com/Studio3T/robomongo/master/src/robomongo/gui/resources/icons/logo-256x256.png)

- [x] **StarUML**
Comment=A sophisticated software modeler
Icon=staruml
[Icon Link](http://staruml.io/image/staruml_logo.png)

- [x] **SVG Cleaner**
Comment=Batch, tunable SVG cleaning program
Icon=svgcleaner
[Icon Link](https://github.com/RazrFalcon/svgcleaner-gui/blob/master/icons/svgcleaner.ico)

- [x] **Portal**
Icon=applications-system-symbolic
[Icon Link]()

- [x] **Help**
Comment=Get help with GNOME
Icon=org.gnome.Yelp
[Icon Link]()

- [x] **Wine Internet Explorer**
Icon=7596_iexplore.0
[Icon Link](https://pt.wikipedia.org/wiki/Ficheiro:Internet_Explorer_9_icon.svg)

- [x] **winebrowser**
Icon=7765_winebrowser.0
[Icon Link]()

- [x] **notepad**
Icon=1E64_notepad.0
[Icon Link]()

- [x] **Wine Installer**
Icon=2402_msiexec.0
[Icon Link]()

- [x] **wordpad**
Icon=97C1_wordpad.0
[Icon Link](http://www.iconarchive.com/show/simply-styled-icons-by-dakirby309/Wordpad-icon.html)

- [x] **rundll32**
Icon=1CD8_rundll32.0
[Icon Link](https://www.flaticon.com/free-icon/dll_354759)

Thanks in advance!

**Comment by bikass** [comment]
Thank you for such nice request with all needed info to make icons :)
I will definitely add those.

**Comment by btd1337** [comment]
@bikass Icons wrong:
- com.github.cryptowyrm.copypastegrab: It's a video downloader
- com.github.ranfdev.raddiu: It's a Radio Player

Old icons to fix:
- Update pcsx2.svg (old style) to PCSX2.svg style. (Use symlink)

Thanks in advance for your great job!

**Comment by btd1337** [comment]
@bikass Photoshop icon is in wrong place:

`Categories/Scalable`

Would It possible fix your location?

**Comment by bikass** [comment]
Hi, no I think, it's in correct place. Why would you like it to be in categories. In all other themes this icon is in apps?

**Comment by btd1337** [comment]
@bikass Look:

https://github.com/bikass/korla/blob/master/korla/categories/scalable/AdobePhotoshop.svg

**Comment by bikass** [comment]
My bad. I dropped by mistake into wrong folder. Fixed
