### ISSUE TITLE
Gnome Notification icon is missing

### ISSUE THREAD

**Issue by btd1337** [bikass/korla#31]
**In Korla:**

![Captura de tela de 2019-06-08 15-34-15](https://user-images.githubusercontent.com/11943860/59151052-3d549880-8a03-11e9-9c8b-7f4bb4c4c577.png)

![Captura de tela de 2019-06-08 15-37-37](https://user-images.githubusercontent.com/11943860/59151057-62490b80-8a03-11e9-997b-0ebe24d86284.png)

**In Newaita Icon Theme:**

![49760979-e4eb4b00-fcac-11e8-99af-cac9097fe6e6](https://user-images.githubusercontent.com/11943860/59151071-89074200-8a03-11e9-8c32-fe774526907f.png)

![49687710-1c5fc900-faee-11e8-845a-c09a613157ef](https://user-images.githubusercontent.com/11943860/59151076-945a6d80-8a03-11e9-8ba7-d7f747916f84.png)

**Comment by bikass** [comment]
Added few missing icons, but on VM, don't have notifications so cant really test.

**Comment by btd1337** [comment]
It still has not worked.
