### ISSUE TITLE
places/folder icons

### ISSUE THREAD

**Issue by bikass** [bikass/korla#32]
Created new places icon sets. Left old ones for now. Do not want to scare those few users who using this theme. 
But maybe we should change. Lets say set 1 or 2 ?
![folders_pic](https://user-images.githubusercontent.com/8824269/59867271-77745180-9396-11e9-94aa-d02c68d92244.jpg)

**Comment by Digitalone1** [comment]
I like the one in the image.

**Comment by bikass** [comment]
Ok, I updated with icons from firs row.

**Comment by Digitalone1** [comment]
Dolphin icon (symlinked to apps/file-manager.svg) is intended to remain the old version?

**Comment by bikass** [comment]
Not intended. Updated to new.

**Comment by Digitalone1** [comment]
I'm trying it. Very beautiful. I worked soon on the desktop while I had to reload the theme from system settings to show new icons inside Dolphin (maybe cache issue).

Anyway, `places/scalable/folder-open.svg` is corrupted.

And `korla/apps/` misses `breeze/apps/64/plasmavault.svg`. Please, draw it your style.

![Screenshot_20190622_132310](https://user-images.githubusercontent.com/25790525/59963263-ee256200-94f0-11e9-9838-c77aca900cdf.png)

**Comment by bikass** [comment]
Ok updated those icons.
I also redid mimetypes icons. Now they are original not from other theme. We also changed so many app icons and I think LaCpitane and Macos11 can be removed from readme. Only icon set is being used is from Papirus theme.

**Comment by Digitalone1** [comment]
Updated. Very nice. But those are the old version:

`korla/mimetypes/scalable/application-x-love-game.svg`
`korla/mimetypes/scalable/application-x-lyx.svg`
`korla/mimetypes/scalable/application-x-virtualbox-vdi.svg`
`korla/mimetypes/scalable/application-x-tsx.svg`

Anyway I see some breeze mimetypes missing in korla:

`breeze/mimetypes/64/application-dicom.svg`
`breeze/mimetypes/64/application-msonenote.svg`
`breeze/mimetypes/64/application-vnd.iccprofile.svg`
`breeze/mimetypes/64/application-vnd.ms-infopath.svg`
`breeze/mimetypes/64/application-vnd.visio.svg`
`breeze/mimetypes/64/application-x-kexi-connectiondata.svg`
`breeze/mimetypes/64/application-x-kdenlivetitle.svg`
`breeze/mimetypes/64/application-x-kvtml.svg`
`breeze/mimetypes/64/application-x-labplot2.svg`
`breeze/mimetypes/64/application-x-ms-shortcut.svg`
`breeze/mimetypes/64/application-x-wmf.svg`
`breeze/mimetypes/64/application-x-skg.svg`
`breeze/mimetypes/64/application-x-skgc.svg`
`breeze/mimetypes/64/x-kde-nsplugin-generated.svg`
`breeze/mimetypes/64/application-xmind.svg`
`breeze/mimetypes/64/image-vnd.dgn.svg`
`breeze/mimetypes/64/image-vnd.djvu.svg`
`breeze/mimetypes/64/image-vnd.dwg.svg`
`breeze/mimetypes/64/image-x-vnd.trolltech.qpicture.svg`
`breeze/mimetypes/64/message-partial.svg`
`breeze/mimetypes/16/radio.svg`
`breeze/mimetypes/64/text-wiki.svg`
`breeze/mimetypes/64/text-x-patch.svg`
`breeze/mimetypes/64/text-x-rpm-spec.svg`
`breeze/mimetypes/64/text-x-tcl.svg`
`breeze/mimetypes/64/x-media-podcast.svg`
`breeze/mimetypes/64/x-office-calendar.svg`

Do you have breeze-icon-theme on your system? Some of them can be symlinked, but don't know which icons to be pointed. Others should be done from scratch.

**Comment by bikass** [comment]
Made it, hope didn't missed anything.

**Comment by Digitalone1** [comment]
> Made it, hope didn't missed anything.

They misses:

`breeze/mimetypes/64/application-vnd.visio.svg`
`breeze/mimetypes/64/application-x-chm.svg`
`breeze/mimetypes/64/application-x-kexiproject-shortcut.svg` (like `application-database.svg`, but it's a shortcut)
`breeze/mimetypes/64/application-x-kplato.svg`
`breeze/mimetypes/16/radio.svg`
`breeze/mimetypes/64/text-x-kotlin.svg`

Meanwhile, I added missing symlinks.

**Comment by Digitalone1** [comment]
That's OK. It misses only radio, but it's not really relevant. You can close.

**Comment by bikass** [comment]
I forgot about radio.svg . I will make it.
