### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by algent-al** [bikass/korla#36]
Hi! Thank you for a great job.
I have some requests, and I hope they will be accepted.
uget.svg and system-software-install.svg are same icons, maybe uget should be updated. They are at:  
```
korla/korla/apps/scalable/uget.svg
korla/korla/apps/scalable/system-software-install.svg 
```
Also please add these icons.
- Simplenote
- FreeCAD

**Comment by bikass** [comment]
Hi, your requested icons fixed and added. 
I'm thinking to push new release in e few days, so if you see some wrong icons or have some requests - don't hesitate :)

**Comment by algent-al** [comment]
That was fast. Thank you!
