### ISSUE TITLE
Thunderbird icon not rendered properly

### ISSUE THREAD

**Issue by ObserverOfTime** [bikass/korla#37]
### How it should look:

![Firefox](https://user-images.githubusercontent.com/24971970/60183058-31077280-982e-11e9-8e72-c88661cf26ab.png)

### How it looks:

![KDE](https://user-images.githubusercontent.com/24971970/60182610-4f20a300-982d-11e9-9518-9886ba943e4c.png)

### Environment info:

* Korla: `master (2b33c6e)`
* Linux: `Antergos 5.1.14-arch1-1-ARCH`
* DE: `KDE Plasma 5.16.1-2`

**Comment by bikass** [comment]
It happens when there are pixel layers. But I opened this file and everything is ok with the icon.
However I did some optimizations, maybe this will help.

**Comment by ObserverOfTime** [comment]
Now it looks OK when selecting it in the menu, but is still broken after applying it.
