### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by ObserverOfTime** [bikass/korla#38]
It'd be nice if you could some of the following icons:

### Missing apps

* [draw.io](https://github.com/jgraph/drawio-desktop)
* [Iridium Browser](https://iridiumbrowser.de/)
* [MKVToolNix GUI](https://gitlab.com/mbunkus/mkvtoolnix) (symlink to `mkv-extractor-gui`?)
* [QComicBook](https://github.com/Uid351324/QComicBook) (symlink to `comix`?)
* [PlantUML](http://plantuml.com/)
* [Rclone Browser](https://github.com/noabody/RcloneBrowser)
* [Typora](https://typora.io/)
* [Zathura](https://git.pwmt.org/pwmt/zathura) (symlink to `acroread`?)

### Missing symlinks

* `apache-netbeans` -> `netbeans`
* `gnvim` -> `neovim`
* `nvim-qt` -> `neovim`
* `org.fontforge.FontForge` -> `fontforge`
* `org.inkscape.Inkscape` -> `inkscape`

**Comment by bikass** [comment]
Made it.
