### ISSUE TITLE
symbolic icon for thunar 1.6.x to 1.8.x and "show desktop" xfce4-panel

### ISSUE THREAD

**Issue by denikris** [bikass/korla#40]
![thunar xfce-pane](https://user-images.githubusercontent.com/16707606/61110437-7627d780-a4b1-11e9-8558-466143e1310a.png)

make icon in side pane and xfce4-panel symbolic, thunar and "show desktop" icon in panel currently use the small folder icon except for "home", "trash" and "devices" (i think) icon

**Comment by bikass** [comment]
Hi, if you could tell me icon names, I will make them.

**Comment by denikris** [comment]
i don't know the name, it's icon for "home", "desktop", "documents", "downloads", "trash", "pictures", "publics", etc in thunar file manager and "desktop" / "show desktop" in xfce4-panel. icon on the left side pane should be symbolic for places and panel icons with 16x16 i think

here screenshot of xfce panel using ubuntu-mono-dark icon
![panel](https://user-images.githubusercontent.com/16707606/61192633-064b6400-a6e0-11e9-8a45-aaf911e5eeb5.png)

and thunar using elementary xfce darkest icon
![thunar](https://user-images.githubusercontent.com/16707606/61192651-35fa6c00-a6e0-11e9-9c1f-b06549607921.png)

**Comment by bikass** [comment]
Hi, I checked other themes on xfce - same thing. It looks like it's how thunar works, nothing I can do.
