### ISSUE TITLE
Scaling issue of Panel icons

### ISSUE THREAD

**Issue by bikass** [bikass/korla#41]
Still have this issue. Sometimes icons just appear bigger..
![Screenshot from 2019-07-17 13%3a02%3a47](https://user-images.githubusercontent.com/8824269/61368515-b2cf4680-a896-11e9-96c5-207b264ce7cd.png)
![Screenshot from 2019-07-17 13%3a08%3a20](https://user-images.githubusercontent.com/8824269/61368522-b793fa80-a896-11e9-8ce5-285af22230a1.png)

I think this is index file issue but I cant find a solution.

**Comment by Digitalone1** [comment]
I think it's a Budgie issue, maybe related to icon cache.

**Comment by bikass** [comment]
Mabye, I don't have this issue on gnome.
