### ISSUE TITLE
WPS Office 2019 (New icons)

### ISSUE THREAD

**Issue by algent-al** [bikass/korla#42]
WPS Office 2019 has been updated recently.
They added PDF support and renamed their .png icons.
For example from `wps-office-etmain.png `to `wps-office2019-etmain.png`

![new wps office icons](https://user-images.githubusercontent.com/46356616/61565029-22505c00-aa78-11e9-8e2e-c14e60a95c5b.png)

**Comment by bikass** [comment]
Thanks! Ok I added those 4 mimetype icons.

**Comment by algent-al** [comment]
May I have your permission to package this icon theme for [Solus](https://dev.getsol.us/T8075) Repository?

**Comment by bikass** [comment]
Yes, that would be really cool. 
I don't know how to do these things my self, so it's really nice that someone is doing it. Thanks!

**Comment by algent-al** [comment]
Thank you!

**Comment by algent-al** [comment]
I did it. Now you will find this icon-theme in Software Center.

**Comment by bikass** [comment]
Yes I see it in Software Center. Cool :)
