### ISSUE TITLE
Fix pdf icon of WPS Office

### ISSUE THREAD

**Issue by algent-al** [bikass/korla#43]
Hi again!
Please add an icon for pdf to korla/apps/scalable following same style as 
![wps](https://user-images.githubusercontent.com/46356616/62494856-b2123c00-b7d4-11e9-9a28-fb133cc1bc63.png)
name should be: "wps-office-pdfmain.svg"
The original png is this:
![wps-office-pdfmain](https://user-images.githubusercontent.com/46356616/62495012-159c6980-b7d5-11e9-88ea-a6313fc0b657.png)

**Comment by bikass** [comment]
Hi, I recently  added pdf icons. Check latest commits if everything is ok.

**Comment by algent-al** [comment]
Yes, but they were mimetypes.

**Comment by bikass** [comment]
Yes in latest commit I made for app as well.

**Comment by algent-al** [comment]
I am not as good as you, but I was looking for something like this, which i did using inkscape.
![wpspdf](https://user-images.githubusercontent.com/46356616/62650481-43a9b700-b957-11e9-8aef-01105635743c.png)
To match the other icon style.
![menu](https://user-images.githubusercontent.com/46356616/62650776-df3b2780-b957-11e9-863b-78bb600104d1.png)
[Here is my job](
https://www.dropbox.com/s/fegghf3k3nahhcq/wps-office-pdfmain.svg?dl=0)

**Comment by bikass** [comment]
:) ok now I understand . I made icons for pdf but also there were icons in mymetypes with the same name. And those were overriding app icons. I deleted mimetype icons, now should be ok.
![Screenshot from 2019-08-07 23%3a10%3a44](https://user-images.githubusercontent.com/8824269/62655142-0e5a9480-b96a-11e9-9b5f-95c2c90c8bca.png)
