### ISSUE TITLE
No icon for LO Math in korla-light

### ISSUE THREAD

**Issue by v6277** [bikass/korla#44]
The icon for LibreOffice Math is missing en korla-light. 

![Screenshot from 2019-08-10 21-40-31](https://user-images.githubusercontent.com/48813136/62829304-348e6780-bbea-11e9-9b21-e3b5d067913d.png)

System: Gnome 3.32

Unrelated: Can a better (or original) icon for TexStudio be used? The one seen in the screenshot is too simplistic.

**Comment by bikass** [comment]
Math icon has been fixed recently, check in latest commits. I remade TEXstudio icon. Not sure is it better now...

**Comment by v6277** [comment]
Just cloned the latest master, the Math icon is fixed thanks! And also, the new TexStudio icon looks so much better! Thank you so much for creating my favorite icon theme!
