### ISSUE TITLE
Contrast on mimetype label

### ISSUE THREAD

**Issue by luni3359** [bikass/korla#45]
Not really a problem, but I think the white on grey text mimetypes are hard to read when small, like ``mimetypes/scalable/application-executable.svg`` and ``mimetypes/scalable/application-7zip.svg``.

**Comment by bikass** [comment]
Ok I 'll check what I can do.

**Comment by algent-al** [comment]
I have also a request about changing a mimetype. 

![document-icons](https://user-images.githubusercontent.com/46356616/65378316-de1b4b00-dcb6-11e9-8cac-73e5f9521c2c.png)

It think it that doc and docx files should be blue. 

It is just a suggestion.

**Comment by bikass** [comment]
@algent-al  this greyish color is used for text files. I don't really want them to change to blue. But maybe
 it could be done like this:
![application-word](https://user-images.githubusercontent.com/8824269/65392123-de304f00-dd79-11e9-8c6f-c56719166a06.jpg)
But this is different design. Icons supposed to be as monochromatic as possible.

@luni3359 If you have big icons they are easily readable. Maybe this text in icons is not needed anyway. It's just leftover from old design.

**Comment by algent-al** [comment]
@bikass I am OK with grey color for text files.
I was asking for DOC and DOCX files.
I am not good with colors but i was thinking about something like this.
![doc](https://user-images.githubusercontent.com/46356616/65392315-c2c24580-dd73-11e9-90c8-13309c0c0393.png)

like you have done with ppt (pptx) and xls (xlsx)

**Comment by bikass** [comment]
Its not difficult to make them blue :) But blue colors are used for image files like png, psd... Now it's easy to make difference. What do you think?

**Comment by algent-al** [comment]
I think that we are used to see, xls green, doc blue and ppt orange.

Adwaita:
![Adwaita](https://user-images.githubusercontent.com/46356616/65441554-e6949280-de2a-11e9-84e2-417be5ea9c5d.png)

Papirus:
![Papirus](https://user-images.githubusercontent.com/46356616/65441593-f613db80-de2a-11e9-885d-676544187013.png)

Numix:
![Numix](https://user-images.githubusercontent.com/46356616/65441616-ff04ad00-de2a-11e9-9f24-f3b221bdaa6a.png)

La Capitaine
![la-capitaine](https://user-images.githubusercontent.com/46356616/65441931-910cb580-de2b-11e9-8b48-d639979b06c7.png)

For my taste i prefer it blue. What ever you decide, it is not problem for me.
Looking forward for release 1.1.9 to package it for Solus.

**Comment by bikass** [comment]
Ok, I made blue icon. Others seems to be seem linked.
