### ISSUE TITLE
acestream-engine icon

### ISSUE THREAD

**Issue by Digitalone1** [bikass/korla#46]
Hello, can you please convert this icon to svg and add it to the theme placing acestream-engine.svg in apps folder? Thanks.

![acestream-engine](https://tivustream.com/wp-content/uploads/2019/05/ace.png)

**Comment by bikass** [comment]
Hi, icon is added.

**Comment by bikass** [comment]
Forgot that. Fixed.

**Comment by Digitalone1** [comment]
Thank you @bikass 

Great work as always.
