### ISSUE TITLE
Office category icon broken on Plasma

### ISSUE THREAD

**Issue by Digitalone1** [bikass/korla#48]
I noticed that:

![Screenshot_20190830_192117](https://user-images.githubusercontent.com/25790525/64040173-b2e08880-cb5c-11e9-9adc-7aaade66c542.png)

Can you fix, @bikass? 

Thanks.

**Comment by bikass** [comment]
Hi, I fixed Office icon.
Recently in VM I was running plasma to check broken icons, but looks like I missed some :)

**Comment by Digitalone1** [comment]
Great. Thanks.
