### ISSUE TITLE
Icone Requste

### ISSUE THREAD

**Issue by APakrohk** [bikass/korla#49]
**DarkTable** :[ WebSite](https://www.darktable.org/) , [WikiPedia](https://en.wikipedia.org/wiki/Darktable)

**MineTest** : [WebSite](https://www.minetest.net/) , [WikiPedia](https://de.wikipedia.org/wiki/Minetest)

**VLC** : [WebSite](https://www.videolan.org/vlc/index.fa.html) , [WikiPedia](https://de.wikipedia.org/wiki/VLC_media_player)

**Wire** : [WebSite](https://wire.com/en/) , [WikiPedia](https://en.wikipedia.org/wiki/Wire_(software))

**Telegram** : [WebSite](https://telegram.org/) , [WikiPedia](https://en.wikipedia.org/wiki/Telegram_(software))

**Firefox Quantum: Developer Edition** : [WebSite](https://www.mozilla.org/en-US/firefox/developer/) , [WikiPedia](https://en.wikipedia.org/wiki/Firefox)

**Kindd** : [**Github**](https://github.com/LinArcX/Kindd)

**Comment by bikass** [comment]
I added Mine Test and Kindd icons. Other icons are already in the theme.

**Comment by APakrohk** [comment]
![Screenshot_20190902_190916](https://user-images.githubusercontent.com/27810360/64122117-ec600080-cdb5-11e9-88c4-20c141725c4b.png)
See the submitted image!
