### ISSUE TITLE
24px emblem-download icon is huge when used in headerbar

### ISSUE THREAD

**Issue by friday** [bikass/korla#5]
[GameHub](https://github.com/tkashkin/GameHub) uses this icon in the headerbar with [24px](https://valadoc.org/gtk+-3.0/Gtk.IconSize.LARGE_TOOLBAR.html) in size. While this is unconventional, the size should not look like this.

![screenshot from 2019-01-12 18-05-38](https://user-images.githubusercontent.com/515120/51076792-a7a81d80-169d-11e9-8436-fad537a637c5.png)

I also think the folders in the main body are too small, but I haven't looked into this.

**Comment by bikass** [comment]
Yes it's not acceptable. I could not find the reason why, I will try later.
Emblem icons has been updated. They should look little bit different than in your screenshot.

**Comment by friday** [comment]
I'm using Korla 0.8.3 (from [here](https://aur.archlinux.org/packages/korla-icon-theme/)).

GameHub just updated yesterday to avoid this (among other things). So if you want to test with this app, you should use an older version (ex https://github.com/tkashkin/GameHub/releases/tag/0.12.1-60-dev)

**Comment by bikass** [comment]
Maybe I found solution. Could You test on your side (pushed to releases 0.8.4)
Not sure is ir right way to do but added these lines in index.theme:
MinSize=8
MaxSize=22

**Comment by friday** [comment]
Yes :+1:  It's now sized normally:

![korla](https://user-images.githubusercontent.com/515120/51086468-8439ad00-1747-11e9-8f25-cc0ebfcb8c57.png)

It's not very easy to see on a dark theme, but this seems to be somewhat common for with non-symbolic icons. Paper and Flat-remix has that problem too.

This should close the issue, but I'll leave it open for you to decide, since there's some more info regarding other potential improvements.

Really nice work btw!
