### ISSUE TITLE
odrive icon

### ISSUE THREAD

**Issue by algent-al** [bikass/korla#51]
Hi! Could you please add another icon for "odrive", the Google Drive client for linux.
There are some icons with name "Google Drive", but the application out of the box requires "odrive".

[Desktop Entry]
Name=Open Drive
Comment=Simple google drive client
Exec="/opt/OpenDrive/odrive" %U
Terminal=false
Type=Application
Icon=odrive
Categories=Archiving;

**Comment by bikass** [comment]
Hi! Odrive icon has been added.
