### ISSUE TITLE
icon request

### ISSUE THREAD

**Issue by N0mi5** [bikass/korla#54]
Id like to request some new icons:
Xournal++ | [GitHub](https://github.com/xournalpp/xournalpp)
deConz | [GitHub](https://github.com/dresden-elektronik/deconz-rest-plugin)
Shattered Pixel Dungeon | [GitHub](https://github.com/00-Evan/shattered-pixel-dungeon)
Noson | [GitHub](https://github.com/janbar/noson-app)

Thanks for the awesome icon theme!

**Comment by bikass** [comment]
Hi, I made icons, except deConz. If you could tell what the icon name should be, and how original icon looks?

**Comment by N0mi5** [comment]
Name=deCONZ
Exec=/usr/bin/deCONZ-autostart.sh
Icon=/usr/share/deCONZ/icons/de_logo_48px.png

Thank you, @bikass !
![deCONZ](https://user-images.githubusercontent.com/17096075/64991634-835aab80-d8d2-11e9-9a59-e78148162eaa.jpg)

**Comment by bikass** [comment]
Made deconz icon. Check in latest commit.
