### ISSUE TITLE
Missing "Home" and "Recent" Icons

### ISSUE THREAD

**Issue by Jont828** [bikass/korla#55]
I'm running Arch and in Nautilus, the Home and Recent folder icons aren't showing. [Here's a link](https://imgur.com/a/9IFIc1P) that shows what I mean.

**Comment by bikass** [comment]
I have nautilus on two different systems and it runs fine.
Try to update cache or restart machine.

**Comment by Jont828** [comment]
I've tried restarting and clearing the cache, and unfortunately it's not working. The Recent and Home icons, however, do show on other icon sets, including an older copy of Korla.

**Comment by bikass** [comment]
Are you using Gnome or Xfce? And how did you installed theme? It could be permission issues.
