### ISSUE TITLE
icon request

### ISSUE THREAD

**Issue by algent-al** [bikass/korla#57]
New firefox icon in v.1.19 are very beautiful.
Please also add:

[firefox-logo-focus](https://commons.wikimedia.org/wiki/File:Firefox_Focus_Logo,_2017.svg)

**Comment by bikass** [comment]
I added icon. Not sure if naming is correct: firefoc-logo-focus.svg

**Comment by algent-al** [comment]
I agree. Maybe it should be firefox-focus. Thank you for adding it.

**Comment by algent-al** [comment]
Please add another icon for cawbird. This app is a fork of corebird. [github page](https://github.com/IBBoard/cawbird).

**Comment by algent-al** [comment]
Also a fix for corebird icon is needed. I placed it to my panel but seems to be a bit higher than other icons there.
![corebird](https://user-images.githubusercontent.com/46356616/66242329-a8885000-e701-11e9-880c-9869a29f2eac.png)

**Comment by bikass** [comment]
There are two main icon shapes circle and square with rounded corners. So I made corebird similar to square. Also there are original icons like firefox, and icons like terminal. Maybe we should change those icons to square template.
I couldn't find cawbird icon so I made up.

**Comment by algent-al** [comment]
The original cawbird icon is [here](https://github.com/IBBoard/cawbird/blob/master/data/hicolor/96x96/apps/uk.co.ibboard.cawbird.png) and it is ugly (i think) . I saw your new icon for cawbird, it looks fine, it is similar to corebird, but using an icon that is more similar to twitter icon is more better since this application is only for twitter, like corebird did. 
However your icon is still good.

**Comment by algent-al** [comment]
Add another icon please.
This is [safeeyes](https://github.com/slgobinath/SafeEyes/blob/master/share/icons/hicolor/128x128/apps/safeeyes.png) which has a menu entry.

There are in korla good panel icons for this app, so only the menu icon is needed.

**Comment by bikass** [comment]
Hi, I made safeeyes icon.
