### ISSUE TITLE
Can I add an icon to "abrt" fedora bug report?

### ISSUE THREAD

**Issue by xzj8b3** [bikass/korla#62]
Can I add an icon to "abrt" fedora bug report?

**Comment by bikass** [comment]
Hi, yes you can add icon.

**Comment by xzj8b3** [comment]
> Hi, yes you can add icon.

![external-content duckduckgo com](https://user-images.githubusercontent.com/26720956/70377412-1cb2c000-190c-11ea-9d4c-102c3502b988.jpg)

**Comment by bikass** [comment]
Cool :) Now you need to make it fit to icon theme. You can put it on a circle or beveled square (use as template from other icons). Make it flat (we don't use 3d icons), remove shadow and glow effects.

**Comment by xzj8b3** [comment]
> Cool :) Ora devi adattarlo al tema dell'icona. Puoi metterlo su un cerchio o su un quadrato smussato (usa come modello da altre icone). Rendilo piatto (non usiamo icone 3d), rimuovi gli effetti di ombra e bagliore.

I'd say it's all right.... maybe it's a Rhythmbox icon magazine that after the last update
