### ISSUE TITLE
new recent KDE icons

### ISSUE THREAD

**Issue by Digitalone1** [bikass/korla#63]
There are new "recent" icons in Breeze theme.

They are located at
* breeze/actions/22/folder-open-recent.svg
* breeze/places/64/folder-recent.svg
* breeze/actions/16/tag-recents.svg

![Screenshot_20191216_103338](https://user-images.githubusercontent.com/25790525/70896007-3761f480-1ff0-11ea-9e09-412a599e2d31.png)

If you can make them for korla, thanks. ;)

**Comment by bikass** [comment]
Hi, I made for actions folder-open-recent.svg
Other two are in the theme or don't they show up properly?

**Comment by Digitalone1** [comment]
So I think folder-open-recent is the only missing. I will check when have time. I see now that you added a new theme, so I have to update the packages on Arch Linux to include it.

I'll let you know.

**Comment by bikass** [comment]
Yes it's just grey folder icons. Didn't know other way how to give option to change folder color, so I made separate theme. Not the best solution. If you don't need grey folder icons you can leave as is.

**Comment by Digitalone1** [comment]
That's OK.
