### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by algent-al** [bikass/korla#64]
Hi. Please add an icon for app [recoll](https://www.lesbonscomptes.com/recoll/)

**Comment by bikass** [comment]
Hi, I did added Recoll icon.

**Comment by algent-al** [comment]
Thank you @bikass. Is korla-pgrey ready or it is just experimental?

**Comment by bikass** [comment]
korla-pgrey is just a grey icons of folders (places). I think it's ready for use.
