### ISSUE TITLE
XPS filetype icon is missing

### ISSUE THREAD

**Issue by SoftExpert** [bikass/korla#67]
Hello,

I wonder if an icon for XPS files (**application/xps** mimetype) can be added.

Thank you in advance for your help !

Best regards,
SoftExpert

**Comment by bikass** [comment]
Hi, I looked at other themes couldn't find anything named xps. Could you provide names of icons you referring?

**Comment by SoftExpert** [comment]
Hi,
Kinda difficult to find an established logo - it's not as "iconic" as PDF.
However, I found something like this [https://www.flaticon.com/free-icon/xps_1088594](https://www.flaticon.com/free-icon/xps_1088594) or this [https://www.file-extension.info/images/resource/formats/xps.png](https://www.file-extension.info/images/resource/formats/xps.png) but I guess you can let your imagination running wild; perhaps use the same icon as for PDF but replace the letters ...

Best regards,
SoftExpert

**Comment by bikass** [comment]
Hi,

I can make icons but I need to know how to name them. Can't find anything named xps.

**Comment by SoftExpert** [comment]
Hi,

Sorry, I did not correctly understood the question previously.
Indeed there seems to be no precedent for this file type in Linux, but if you can use the same naming convention as for the pdf file, we might have a name: **application-xps.svg**.
It seems to respect also the [Icon naming convention](https://specifications.freedesktop.org/icon-naming-spec/icon-naming-spec-latest.html).
Would that be OK?

Best regards,
Marian

**Comment by bikass** [comment]
Hi, I made icon. You can check if it works (in latest commit).

**Comment by SoftExpert** [comment]
Hi,

Looks perfect for me !  Thank you very much !

Best regards,
SoftExpert
