### ISSUE TITLE
Icon request

### ISSUE THREAD

**Issue by algent-al** [bikass/korla#68]
Hi! Plase add an icon for:
[crow-translate](https://github.com/crow-translate/crow-translate/blob/master/dist/unix/generic/hicolor/72x72/apps/crow-translate.png)
[bombermaaan](https://dev.getsol.us/source/bombermaaan/browse/master/files/bombermaaan.svg) here i have added myself an customized icon.

Also if you can, please fix xls mimetype icon, by adding a text "xls" in white color inside the icon like the "doc" for doc mimetypes.
![xls-mimetype](https://user-images.githubusercontent.com/46356616/74103223-bf74fe00-4b4a-11ea-9fcc-6eb13b9e15f5.png)

**Comment by bikass** [comment]
Hi, fixed xls and added bomermaaan.
Crow translate is already in the theme:
https://github.com/bikass/korla/blob/master/korla/apps/scalable/crow-translate.svg

**Comment by bikass** [comment]
Can I ask you something. Long ago I asked solus team to include DJV to repositories. But no one did it. If is not difficult could you maintain it?
https://darbyjohnston.github.io/DJV/

**Comment by algent-al** [comment]
I can try to package it. About maintaining you have to use it, because you have to check if it is working correctly or not.

**Comment by bikass** [comment]
OK, thanks. Its sequence and video player simple to test :)

**Comment by algent-al** [comment]
I am sorry, I tried to package this but seems it needs a PC with a graphical card and I don't have it.
[here](https://www.dropbox.com/s/5y7070jgmkev18w/djv-2.0.5-1-1-x86_64.eopkg?dl=0) is a convertion from .deb to .eopkg. 
Compiled it also in my machine following the developers instructions and in the end after two hours i get same error message in terminal, like the convention from .deb to .eopkg file.

**Comment by algent-al** [comment]
Try to talk to this [guy](https://github.com/cantalupo555/repo-solus/). He is doing some unofficial stuff lately.

**Comment by bikass** [comment]
Thank you, for your help! Not a big deal, I'm thinking to switching to fedora anyway :)

**Comment by algent-al** [comment]
If so, I think you will be back on Solus.

**Comment by algent-al** [comment]
Hi! By the way this [djv](https://www.dropbox.com/s/5y7070jgmkev18w/djv-2.0.5-1-1-x86_64.eopkg?dl=0) that i have builded earlier, is working in my work PC.
![djv](https://user-images.githubusercontent.com/46356616/82884404-f5948d00-9f43-11ea-8d12-10299522c3d1.png)
Could not try this on my home PC, because it has old hardware.

**Comment by bikass** [comment]
Hi! It is nice to hear :) BTW they recently released 2.0.6 version.

**Comment by algent-al** [comment]
Yes, I know. Wrote again about this, since I was surprised that I it was working. Was just about to delete it, but thought let's try here (in my work PC).
It is basically and just conversion from DEB to EOPKG. That it can be done very easy.
If you want the 2.0.6, I can do it again tomorrow, when I go to work again.
Best thing it would be if you learn how to do it.

**Comment by algent-al** [comment]
[djv-2.0.6-1-1-x86_64.eopkg](https://www.dropbox.com/s/nhca31cmyp95z5b/djv-2.0.6-1-1-x86_64.eopkg?dl=0)
