### ISSUE TITLE
Desktop folder show little

### ISSUE THREAD

**Issue by JackCloudman** [bikass/korla#7]
I use xfce and all icons see fine, but folder icons and trash icon show very little, if i change icon size the folder icon not change.
![image](https://user-images.githubusercontent.com/17970185/52234165-a4601600-2886-11e9-9bd5-25798a4311a9.png)

**Comment by bikass** [comment]
Hi,
To be honest I do not support all DEs. I'm trying to make it work on Budgie (so it should work on Gnome). Other user Giusy Digital made it work on KDE. If  you want, you welcome to improve theme on xfce.
