### ISSUE TITLE
applications icon in gnome 3.36.0

### ISSUE THREAD

**Issue by algent-al** [bikass/korla#70]
Application icon on gnome point to a new file.  
Found this on new adwaita theme.  
`/usr/share/icons/Adwaita/scalable/apps/preferences-desktop-apps-symbolic.svg`

![applications](https://user-images.githubusercontent.com/46356616/76960833-8df70b80-691c-11ea-9e61-31e507cc3984.png)

**Comment by bikass** [comment]
Hi, it is weird that icon is "parental control". Maybe it is another icon symelinked to this one. I remember on Solus I couldn't find this icon, it is also in menu. In fedora gnome 2.34 there is no such entry as "applications" so I can not test right now. Maybe you could create some random icon with that name and check if it works?

**Comment by algent-al** [comment]
Hi! i have edited, the issue. It is not parantal icon, but i suspect it is this one `/usr/share/icons/Adwaita/scalable/apps/preferences-desktop-apps-symbolic.svg`.

[Here](https://dev.getsol.us/R340:6f7304c84e78095afe8d40f1bd6325a5d73c6a9e) you have the changelog of adwaita-gtk-theme on Solus, form 3.34.0 ti 3.36.0.

**Comment by algent-al** [comment]
I have done a symlink but now i get a white icon 
![scr](https://user-images.githubusercontent.com/46356616/76966074-addefd00-6925-11ea-9f3c-6eec3be740ac.png)

Probably wrong symlink.

**Comment by algent-al** [comment]
I did a test. Used `0ad.svg` icon and copied it with a new name `preferences-desktop-apps-symbolic.svg` in `korla/apps/scalabe` folder.  
![scre](https://user-images.githubusercontent.com/46356616/76968422-27c4b580-6929-11ea-8f2b-ec54c452d03c.png)
Then updated icon cache.

But in the setting the icon looks different:  
![0ad](https://user-images.githubusercontent.com/46356616/76968539-5d699e80-6929-11ea-96b6-35ea37bde220.png)

**Comment by bikass** [comment]
Well, at least we know what icon it is. And most likely it should be monochromatic, like other symbolic icons. But this is wrong to show symbolic icon with other normal icons. 
Lets say this is a mistake or bug of Solus.

**Comment by algent-al** [comment]
Hi! I see that the this icon is fixed with this commit fee9591
![applications-icon](https://user-images.githubusercontent.com/46356616/79048966-094c9400-7c21-11ea-8a5e-09b2207b32a3.png)

**Comment by bikass** [comment]
:) hm that's weird. I didn't do anything specifically to fix this issue. I guess it's preferences-desktop-apps.svg
I changed to different icon, could you check if it works?

**Comment by algent-al** [comment]
Yes it is working.

    cd /usr/share/icons/korla/apps/scalable
    sudo ln -sv applications-system.svg preferences-desktop-apps.svg
This fixes the icon problem.

This icon stay as it is:
![icon1](https://user-images.githubusercontent.com/46356616/79054141-c00d3c00-7c42-11ea-9e03-de9abefffbd3.png)

This is updated:
![icon2](https://user-images.githubusercontent.com/46356616/79054152-cb606780-7c42-11ea-8e7d-0d355e220c22.png)

And menu icon:
![icon3](https://user-images.githubusercontent.com/46356616/79054170-04004100-7c43-11ea-92e1-780616f3133b.png)

For me this is OK.
