### ISSUE TITLE
Clementine icon on Plasma dark panel

### ISSUE THREAD

**Issue by MrNanook** [bikass/korla#73]
Hi, first of all thanks for this wonderful icon pack!

I have some problems with the Clementine icon on my Plasma dark panel (system tray), using Kora Light:

![clementine-light](https://user-images.githubusercontent.com/33689796/79351336-d7953f00-7f38-11ea-9631-f75262dbeea3.png)

Only a kind of black half-circle is visible.

**Comment by bikass** [comment]
Hi,
Unfortunately I'm not maintaining panel, actions, status icons. They are taken from Papirus theme. Looked into panel icons and clementine is there. Not sure why it is not shown correctly.
I would like to have fully independent theme, but have no idea how to make these icons (I mean, technical side of things).

**Comment by MrNanook** [comment]
Ah, ok, thanks for your response. I'll look into the Papirus panel icons.
