### ISSUE TITLE
Icons request

### ISSUE THREAD

**Issue by mateus96mt** [bikass/korla#74]
- [ ] **Qt 5 Assistant**
Icon=assistant-qt5
[Icon Link]()

- [ ] **Calf Plugin Pack for JACK**
Comment=Process and produce sounds using a set of plugins with JACK interface
Icon=calf
[Icon Link]()

- [ ] **Dock**
Comment=Ubuntu Dock Settings
Icon=preferences-ubuntu-panel
[Icon Link]()

- [ ] **ParaView Client**
Comment=ParaView allows viewing of large data sets
Icon=paraview
[Icon Link](https://p7.hiclipart.com/preview/1008/99/771/paraview-data-visualization-kitware-computer-icons-thirdparty-source.jpg)

- [ ] **Livepatch**
Comment=Manage Canonical Livepatch
Icon=livepatch
[Icon Link](https://res.cloudinary.com/canonical/image/fetch/f_auto,q_auto,fl_sanitize,w_60,h_60/https://dashboard.snapcraft.io/site_media/appmedia/2016/08/pictogram-upgrade-orange-hex.svg.png)

- [ ] **Netflix**
Icon=chrome-eppojlglocelodeimnohnlnionkobfln-Default
[Icon Link]()

**Comment by bikass** [comment]
Icons are added.
