### ISSUE TITLE
Outdated AUR package

### ISSUE THREAD

**Issue by Digitalone1** [bikass/korla#76]
Hello everyone. 

First of all, @bikass, thank you for this great icon theme, it's beautiful, I love it and I'm using it from more than a year on Plasma, it's far more better than Breeze.

I open this issue to inform that the repository for korla stable releases I was maintaining on [AUR](https://aur.archlinux.org/packages/korla-icon-theme) is outdated and unfortunately it won't be updated because I was banned by moderators.

I won't explain why they made this decision, it's not a matter of this issue. I just want to say if someone is using the theme on Arch Linux and can adopt the package, that would be great for those people who were installing korla from AUR and now can't get the new stable updates. The git package is still working and I made a custom one for my system, but the majority of users were installing the stable one.

If someone will adopt it, please close this issue. Thanks.

**Comment by bikass** [comment]
Hello,

Thank you, for helping with theme creation. Nice to hear that you still using this theme. 
So, should I remove instructions for Arch linux in readme file?

**Comment by Digitalone1** [comment]
Yes if you want, leave at least only the git one since it can install the latest commit.

**Comment by Digitalone1** [comment]
Can you leave this open so someone can see it and maybe adopt the package? If it's not a disturb to you @bikass.

**Comment by D3S0X** [comment]
Hello,

I would provide myself as maintainer. My current packages: https://aur.archlinux.org/packages/?SeB=m&K=D3SOX

I personally use this icon pack and I have this repository set to watch releases so I can update the package whenever there is a new version.
Long story short: I would adopt the package

**Comment by Digitalone1** [comment]
Thank you @D3S0X.

Anyway I see there's already a pending request to adopt it, but mods didn't assign it yet. You can try to add also your request.

**Comment by D3S0X** [comment]
> Thank you @D3S0X.
> 
> Anyway I see there's already a pending request to adopt it, but mods didn't assign it yet. You can try to add also your request.

I think it is an orphan request because you can't request to adopt a package. Can you add me as co-maintainer or disown the package and so I can adopt it?

**Comment by Digitalone1** [comment]
> I think it is an orphan request because you can't request to adopt a package. Can you add me as co-maintainer or disown the package and so I can adopt it?

No, I'm banned, can't do nothing on that site.

**Comment by D3S0X** [comment]
> > I think it is an orphan request because you can't request to adopt a package. Can you add me as co-maintainer or disown the package and so I can adopt it?
> 
> No, I'm banned, can't do nothing on that site.

Why are you banned from the AUR? 😲
Is there a way to contact the AUR moderators? The requests on these 2 packages have been around for a long time now and still nothing has been done...

**Comment by Digitalone1** [comment]
I made a mistake in updating a package I owned and they banned me for vandalism.

You can contact them through mailing list I think.

**Comment by D3SOX** [comment]
I got the package. This can be closed.

**Comment by Digitalone1** [comment]
Thank you.
