### ISSUE TITLE
Breeze disk-quota icons missing

### ISSUE THREAD

**Issue by Digitalone1** [bikass/korla#77]
I noticed 4 Breeze **disk-quota** icons used by Plasma addon related to [quota-tools](https://www.archlinux.org/packages/extra/x86_64/quota-tools/) are missing in korla.

All of them are inside **status** folder.

![Screenshot_20200506_150417](https://user-images.githubusercontent.com/25790525/81180796-cecde100-8fab-11ea-9b1c-fa4bf5a00119.png)

**Comment by bikass** [comment]
Hi, I add these icons in to 'status' folder.

**Comment by Digitalone1** [comment]
Is there a way to get them more visible?

![Screenshot_20200506_185644](https://user-images.githubusercontent.com/25790525/81205744-6989e800-8fcb-11ea-9901-5ca45b9738ee.png)

Did you change something to panel configuration? With the latest commit I see korla touchpad icon on the Plasma panel. I thought korla icons would never show on Plasma panel, but it's happening for some icons. I tried to copy disk-quota icons to panel folder, but they won't show. Maybe they have to be redefined to be 24x24 size?

**Comment by bikass** [comment]
Well... before I thought that I could work on panel icons I changed configuration just to one folder. It's in latest release. Algient pointed to some disadvantages so I reverted back to folders with different sizes - in commits.
Quata icon is the Icon I made. But did them symbolic style. Mabye they should be just regular icons.
P.S that Atom is awesome :)

**Comment by Digitalone1** [comment]
Try to make regular icons in status and then a 24x24 version inside panel/24. I'll check if they works. 

input-touchpad icons are showing on my panel, so disk-quota should work too, but maybe they have to be 24x24, otherwise Plasma refuses them.

**Comment by Digitalone1** [comment]
Yes, atom is awesome, search in folder con replace text in en entire project, can be also destructive if not used carefully.

**Comment by bikass** [comment]
I changed disk quota icons to regular, not 24 for now. Check if they show up correctly. Panel does have 16, 22, 24, but those icons fro Papirus

**Comment by Digitalone1** [comment]
Good. We can discuss on panel icons in another topic. Unfortunately I'm busy and can't contribute very much, but I can give an help in free time. With atom you can make big changes very fast, hope this helps in the future.
