### ISSUE TITLE
KDE support?

### ISSUE THREAD

**Issue by Vistaus** [bikass/korla#8]
Hello,

I love your beautiful icon theme! But it does not seem to support KDE. Things like folder icons are missing :( Could you add KDE support please? :)

**Comment by bikass** [comment]
Everything works on Kubuntu.

**Comment by Vistaus** [comment]
Not for me. Just tried reinstalling Korla, but folder icons still aren't showing in Dolphin. That is: it shows the Breeze folder icons (other apps do change though, so the icon theme is applying).
