### ISSUE TITLE
Action icons in light theme

### ISSUE THREAD

**Issue by Digitalone1** [bikass/korla#80]
So I'd like to try to copy and paste all action icons from korla to korla-light and change color using atom.

@bikass can you please tell me what I have to change and where specifically inside the file? Thanks

**Comment by bikass** [comment]
I think it should be in Korla-light-panel. Korla-light is for light themes with dark panel and Korla-light-panel is light theme with light panel.
In Korla-light-panel "actions" icons are already dark (linked to Korla-light "actions"). What you should try changing is status-symbolic. So, to make 'status' folder unique, symlink 'scalable'  to Korla/status/scalable and 'symbolic' make dark.

**Comment by bikass** [comment]
Oh, one more thing... I have redone all symbolic icons in Korla. Like actions/simbolic must be changed. now they are dark but from Papirus... what a mess :)

**Comment by Digitalone1** [comment]
> Oh, one more thing... I have redone all symbolic icons in Korla. Like actions/simbolic must be changed. now they are dark but from Papirus... what a mess :)

I was talking about them.

Is there a color property that I can change in all files? If yes, tell me which one and the new value.

**Comment by bikass** [comment]
Dark color hex #444444 , or rgb(68,68,68)

**Comment by bikass** [comment]
Just silly question, if you do changes I should do 'git pull' or something else? 

Also about cleaning svg files I'm using [scour.sh](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/blob/master/tools/_scour.sh) from papirus dev team but I always getting this top line which  I need to delete manually...

<!DOCTYPE svg  PUBLIC '-//W3C//DTD SVG 1.1//EN'  'http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd'>

... if you know any way to avoid this line - would be really cool.

Another think if you know a way to make svg code look like this would be even more cooler :)

<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16">
 <defs>
  <style id="current-color-scheme" type="text/css">
   .ColorScheme-Text { color:#dfdfdf; } .ColorScheme-Highlight { color:#4285f4; }
  </style>
 </defs>
 <path style="fill:currentColor" class="ColorScheme-Text" d="M 8 1 C 4.137 1 1 4.137 1 8 C 1 11.863 4.137 15 8 15 C 11.863 15 15 11.863 15 8 C 15 4.137 11.863 1 8 1 z M 8 3 C 9.0194 3 9.959 3.28763 10.75 3.8125 L 3.8125 10.75 C 3.28763 9.95898 3 9.0194 3 8 C 3 5.2407 5.2408 3 8 3 z M 12.1875 5.25 C 12.71237 6.04102 13 6.9806 13 8 C 13 10.7592 10.7592 13 8 13 C 6.9806 13 6.041 12.71237 5.25 12.1875 L 12.1875 5.25 z"/>
</svg>

**Comment by Digitalone1** [comment]
I think something like `git fetch master`

**Comment by Digitalone1** [comment]
> !DOCTYPE svg PUBLIC '-//W3C//DTD SVG 1.1//EN' 'http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd'
> 
> ... if you know any way to avoid this line - would be really cool.

This can be cleaned with atom search in folder and replace with empty text

**Comment by Digitalone1** [comment]
@bikass did you notice any issue with the modified icons?

**Comment by bikass** [comment]
I think everything is fine. I fixed some icons, I guess they had different color. Thank you.
