### ISSUE TITLE
Add icon guvcview pleace

### ISSUE THREAD

**Issue by xzj8b3** [bikass/korla#84]
![Schermata da 2020-06-04 16-13-52](https://user-images.githubusercontent.com/26720956/83767970-88d56d00-a67e-11ea-8d04-0ad69ea7f895.png)
Could you add a prettier icon for that software?

[]Guvcview download (https://sourceforge.net/projects/guvcview/)

**Comment by bikass** [comment]
Hi, icon is in the theme:
https://github.com/bikass/korla/blob/master/korla/apps/scalable/guvcview.svg

**Comment by xzj8b3** [comment]
> Hi, icon is in the theme:
> https://github.com/bikass/korla/blob/master/korla/apps/scalable/guvcview.svg

Tanks
