### ISSUE TITLE
Missing Breeze emblems

### ISSUE THREAD

**Issue by Digitalone1** [bikass/korla#85]
Hello, I switched to Gnome Shell and I'm still using korla which looks very good also in this DE.

However I'm still using Dolphin too and some new emblems came out showing Breeze version.

These are the emblems in Breeze:

![Schermata del 2020-06-08 22-26-56](https://user-images.githubusercontent.com/25790525/84077858-3a0a3900-a9d8-11ea-9e89-d071ed1730ea.png)
![Schermata del 2020-06-08 22-27-41](https://user-images.githubusercontent.com/25790525/84077861-3aa2cf80-a9d8-11ea-8dff-b7be739b4107.png)
 
The following icons are missing in korla

- [x] breeze/emblems/16/newer.svg
- [x] breeze/emblems/16/noninstalled.svg
- [x] breeze/emblems/16/outdated.svg
- [x] breeze/emblems/16/package-available-locked.svg
- [x] breeze/emblems/16/package-available.svg
- [x] breeze/emblems/16/package-broken.svg
- [x] breeze/emblems/16/package-downgrade.svg
- [x] breeze/emblems/16/package-install-auto.svg
- [x] breeze/emblems/16/package-install.svg
- [x] breeze/emblems/16/package-installed-locked.svg
- [x] breeze/emblems/16/package-installed-outdated.svg
- [x] breeze/emblems/16/package-installed-updated.svg
- [x] breeze/emblems/16/package-new.svg
- [x] breeze/emblems/16/package-purge.svg
- [x] breeze/emblems/16/package-reinstall.svg
- [x] breeze/emblems/16/package-remove-auto.svg
- [x] breeze/emblems/16/package-remove.svg
- [x] breeze/emblems/16/package-upgrade-auto.svg
- [x] breeze/emblems/16/package-upgrade.svg
- [x] breeze/emblems/16/rating-unrated.svg
- [x] breeze/emblems/16/rating.svg
- [x] breeze/emblems/16/unrequired.svg
- [x] breeze/emblems/16/vcs-added.svg
- [x] breeze/emblems/16/vcs-conflicting.svg
- [x] breeze/emblems/16/vcs-locally-modified-unstaged.svg
- [x] breeze/emblems/16/vcs-locally-modified.svg
- [x] breeze/emblems/16/vcs-normal.svg
- [x] breeze/emblems/16/vcs-removed.svg
- [x] breeze/emblems/16/vcs-update-required.svg

Can you please add theme? Some have just to be symlinked, others to be made from scratch.

**Comment by bikass** [comment]
Hi, I made these icons. Hope I didn't missed any.

**Comment by Digitalone1** [comment]
Thanks, I'll test them tomorrow and let you know.

**Comment by Digitalone1** [comment]
Made a PR with adjustments. There are only two issues:

![Schermata del 2020-06-10 11-50-30](https://user-images.githubusercontent.com/25790525/84253799-a8521700-ab10-11ea-9fbd-5382f768deb6.png)
 
package-new and rating are corrupted.

**Comment by bikass** [comment]
Fixed broken icons.

**Comment by Digitalone1** [comment]
Thanks.
