### ISSUE TITLE
WPS Writer: wrong icon

### ISSUE THREAD

**Issue by Vistaus** [bikass/korla#9]
As you can see in the attached screenshots, in KDE Menu Editor, the WPS Writer icon shows a different icon than the one actually showing on the panel. All other icons in the menu editor are the same as the ones showing up on the panel, though, so this is an issue with the WPS Writer icon.
![screenshot_20190207_201016](https://user-images.githubusercontent.com/1716229/52436583-f6b66680-2b14-11e9-8e85-f95174479b43.png)
![screenshot_20190207_201054](https://user-images.githubusercontent.com/1716229/52436585-f6b66680-2b14-11e9-8cb6-014d00524c6c.png)

**Comment by bikass** [comment]
:)
Well can't fix when it works :) . I also checked other themes, same icons/
![screenshot_20190207_232621](https://user-images.githubusercontent.com/8824269/52444243-7998ea80-2b30-11e9-8404-a9328460c1ac.png)

**Comment by Vistaus** [comment]
Then why doesn't it work for me? If I apply other themes, the icon changes correctly, so it's got to be a bug in your theme.

**Comment by bikass** [comment]
Might be a bug. This theme is far from perfect.
