### ISSUE TITLE
New PulseEffects icon

### ISSUE THREAD

**Issue by Digitalone1** [bikass/korla#93]
PulseEffects icon has been updated: https://github.com/wwmm/pulseeffects/blob/master/data/pulseeffects.svg

@bikass if you want, you can add it to korla or make a new one better.

**Comment by luni3359** [comment]
Wow, that icon really needs to be fixed on their side.

**Comment by Digitalone1** [comment]
Thanks.

**Comment by Digitalone1** [comment]
@bikass can you please add shadow like the original one? Thanks.

**Comment by Digitalone1** [comment]
Nice.
