### ISSUE TITLE
Release 2.0.0

### ISSUE THREAD

**Issue by algent-al** [bikass/korla#94]
Hey @bikass 
You have released two versions of korla: 1.3.0 and 2.0.0. Which one should I use for the next update?

**Comment by bikass** [comment]
Hi, both are same but correct number 1.3.0. Couldn't find how to delete release.

**Comment by Digitalone1** [comment]
@bikass try following [this](https://devconnected.com/how-to-delete-local-and-remote-tags-on-git/) locally and push.

If you have errors in the terminal, report here.

**Comment by Digitalone1** [comment]
Tag deleted.

Next time, do `git push --delete origin v2.0.0` from terminal.
