### ISSUE TITLE
tresorit icon

### ISSUE THREAD

**Issue by Digitalone1** [bikass/korla#95]
Can you please add this with your style and place it in `apps/scalable/tresorit.svg`? Thanks.

![Schermata del 2020-09-11 21-21-07](https://user-images.githubusercontent.com/25790525/92964778-fa3e6c00-f474-11ea-9e37-7c249688d05b.png)

**Comment by bikass** [comment]
Hi ok I added icon.
And I accidentally included hicolor folder. And don't know how to remove. A little help needed :)

**Comment by Digitalone1** [comment]
Thanks. Renamed.

**Comment by Digitalone1** [comment]
@bikass next time if you have to delete a folder wrongly added:

```
git rm hicolor
git push
```

from terminal

**Comment by Digitalone1** [comment]
@bikass if you have issues in pushing your modifications, rather than doing `git push` do `git push -f`.

**Comment by bikass** [comment]
:) Ok, thank you!
