### ISSUE TITLE
Add two icons, please

### ISSUE THREAD

**Issue by CavaleriOmar** [bikass/korla#96]
Would it be possible to add Ren'Py icon to the (otherwise perfect) icons theme?
And maybe even the EndeavourOS logo? It would be the best, thanks.

**Comment by bikass** [comment]
Hi, added ren'py and EndeavourOS icons.
Is endeavouros.svg right naming of icon?

**Comment by CavaleriOmar** [comment]
Great!

> Is endeavouros.svg right naming of icon?

Yes!

**Comment by CavaleriOmar** [comment]
I've seen the icons: they're so cool!

Thanks a lot!

**Comment by PoorPocketsMcNewHold** [comment]
Don’t forget closing the issue once done.
