### ISSUE TITLE
New Edge icon

### ISSUE THREAD

**Issue by Digitalone1** [bikass/korla#97]
Microsoft Edge browser has been released for Linux also. Can you add the icon to the theme? Thanks.

It seems that the logo is covered by copyright, but you may modify it a little to be your work.

https://upload.wikimedia.org/wikipedia/it/9/98/Microsoft_Edge_logo_%282019%29.svg

**Comment by bikass** [comment]
Hi, made slightly modified icon. What naming of icon should be, I saved as "edge.svg"?

**Comment by Digitalone1** [comment]
No, should be `microsoft-edge.svg`

But please, make also the dev version named `microsoft-edge-dev.svg`:

![microsoft-edge-dev](https://user-images.githubusercontent.com/25790525/97078783-c10a2780-15ee-11eb-8773-6b91ee1da757.png)

Thanks!

**Comment by Digitalone1** [comment]
Great.
