### ISSUE TITLE
Improvement to Kate icon

### ISSUE THREAD

**Issue by Digitalone1** [bikass/korla#98]
Hello @bikass, I usually switch applications under Gnome with alt+tab and noticed that Kate icon has a different size comparing to Firefox and Atom.  

As you can see from the screenshot below, Kate circle is bigger and it seems also a little bit squeezed (but that can be only my impression). 

![Schermata del 2020-12-25 15-54-02](https://user-images.githubusercontent.com/25790525/103137595-737f6900-46ca-11eb-8a3a-e7e8604b9cea.png)

Can you make it similar to Firefox and Atom? 

Thanks.

**Comment by bikass** [comment]
Hi, everything is fine with icon in theme. But this icon is not from theme. Looks different.

**Comment by Digitalone1** [comment]
Can you resize to have a similar width/height of atom/firefox?

**Comment by bikass** [comment]
It is right size, like Atom. You just seeing wrong icon. Check in folder Korla/apps/scalable

**Comment by Digitalone1** [comment]
Anyway, if you look [here](https://github.com/bikass/korla/blob/master/korla/apps/scalable/kate.svg) and then see the screenshot, it's clearly squeezed. I wonder why it's not happening with atom.

**Comment by bikass** [comment]
I don't know how to help you :) in link you sent from theme looks good for me and in your screenshot icon is from other theme :
![Capture](https://user-images.githubusercontent.com/8824269/103138024-df67ce80-46d6-11eb-972f-7c929b6b0b4a.PNG)

**Comment by Digitalone1** [comment]
Maybe I understood why. Kate its showing a separate session for every window started, indeed the default icon on the dock is from korla, but the session specific one belongs to the original which I think is a png.

I'll try to find a workaround to show the right icon.

**Comment by Digitalone1** [comment]
Found out the solution: https://www.reddit.com/r/gnome/comments/kgmngf/how_to_better_integrate_the_kate_text_editor/

![Schermata del 2020-12-25 16-47-52](https://user-images.githubusercontent.com/25790525/103138253-04594300-46d1-11eb-8db6-dbb85edb5a58.png)

Cheers!

Merry Christmas and happy new year @bikass.

**Comment by bikass** [comment]
Cool. There are some apps that doesn't respect theme icons. There was a user always complaining about some DVD app with the same issue :)
Merry Christmas! And happy New Year!
